### ISSUE TITLE
Windows11无法运行

### ISSUE THREAD

**Issue by Littleweisheit** [Mzdyl/LiteLoaderQQNT_Install#1]
.\install_windows.exe
Error loading Python DLL 'C:\Users\ _USERNAME_ \Desktop\_internal\python312.dll'.
LoadLibrary: 找不到指定的模块。

**Comment by Mzdyl** [comment]
[install_windows.exe.zip](https://github.com/Mzdyl/LiteLoaderQQNT_Install/files/14018923/install_windows.exe.zip)
如若可以请尝试一下这个版本，集成了更多依赖

**Comment by heerxingen** [comment]
有没有可能是你安装的不是python3.12 doge
