### ISSUE TITLE
打开qq报错

### ISSUE THREAD

**Issue by wlwxj** [Mzdyl/LiteLoaderQQNT_Install#100]
### 问题类型
请选择一个:
- [ *] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [ ] macOS
- [ ] Linux
- [* ] Windows

### 运行版本
请填写您的运行版本:

### 描述
简要描述您的问题:
安装完打开报错
### 错误截图
请粘贴错误截图:
![image](https://github.com/user-attachments/assets/a04e4085-8432-43b3-b0fd-cbfc62c5f105)

![image](https://github.com/user-attachments/assets/6e5a3ddc-0ffa-470a-aff5-9c331f146f47)

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by Mzdyl** [comment]
请测试以下版本
https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/10277772061/artifacts/1783900423

（印象中 LL 会根据环境变量自动创建目录，不知为啥现在好像没了，还是我记错了？补了个设定的目录不存在自动创建
