### ISSUE TITLE
macOS脚本安装失败

### ISSUE THREAD

**Issue by Gongsc** [Mzdyl/LiteLoaderQQNT_Install#102]
### 问题类型
请选择一个:
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [x] macOS
- [ ] Linux
- [ ] Windows

### 运行版本
请填写您的运行版本:
脚本：1.14
qq版本：6.9.51-26339

### 描述
碰到两个问题：
1. 下载失败，wget下载没加--no-check-certificate参数
2. 手动修改wget参数后继续执行，报了一堆“File name too long”的错

安装完成后，qq没有弹出登录界面，删除所有plugins依旧如此，清空插件重装qq然后重新执行脚本就可以了

### 错误截图
问题1：
<img width="1523" alt="image" src="https://github.com/user-attachments/assets/a4bd7d02-939a-40e8-8168-84beb4422183">
问题2：
<img width="1530" alt="image" src="https://github.com/user-attachments/assets/28ec2c6d-a145-45c6-a624-167eb27087c2">

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by Mzdyl** [comment]
`安装完成后，qq没有弹出登录界面，删除所有plugins依旧如此，清空插件重装qq然后重新执行脚本就可以了`
是liteloaderQQNT 的bug https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/367 https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/361

`下载失败，wget下载没加--no-check-certificate参数`
emmm，请尝试安装 ca-certificates 或 更新 openssl，正常情况下 wget 下载 GitHub 网站不存在证书问题

`手动修改wget参数后继续执行，报了一堆“File name too long”的错`
至于这个问题，不太确定，我检查下代码再说

**Comment by 1amfine2333** [comment]
用测试版，我用测试版sh直接成了
```
# Git通道(mac/linux)
curl -L "https://github.com/Mzdyl/LiteLoaderQQNT_Install/raw/main/install.sh"| bash
```
