### ISSUE TITLE
MacOS使用终端安装无效

### ISSUE THREAD

**Issue by Aboceder** [Mzdyl/LiteLoaderQQNT_Install#103]
### 问题类型
请选择一个:
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [x] macOS
- [ ] Linux
- [ ] Windows

### 运行版本
请填写您的运行版本:6.9.52-26909

### 描述
简要描述您的问题:MacOS使用终端安装，没有任何报错但是QQ界面买有显示LiteLoaderQQNT，重启QQ也一样没有效果
### 错误截图
请粘贴错误截图:
![2024-08-10 at 11 58 12@2x](https://github.com/user-attachments/assets/ed30a2ed-ad19-4b8d-8536-7ec2e299c41d)

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by Aboceder** [comment]
补充：我是卸载了原来的qq，从官网下载的船新版本

**Comment by Mzdyl** [comment]
<img width="905" alt="截屏2024-08-10 14 11 48" src="https://github.com/user-attachments/assets/23ed20f6-5f64-468d-acd0-6b9018cd50ed">
常见问题写了，终端没有权限，请进设置赋予权限

**Comment by Aboceder** [comment]
谢谢，解决了
