### ISSUE TITLE
安装器在python3.9-或win10-不可用

### ISSUE THREAD

**Issue by model-err** [Mzdyl/LiteLoaderQQNT_Install#104]
### 问题类型
请选择一个:
- [✔] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [ ] macOS
- [ ] Linux
- [✔] Windows

### 运行版本
请填写您的运行版本:
py脚本
### 描述
简要描述您的问题:
脚本不支持python3.9-,群友亲测...
麻烦写在readme里...
### 错误截图
请粘贴错误截图:
见群
若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:
建议在readme注明，win10-/python3.9-不可运行
要么去修(

**Comment by LY-Xiang** [comment]
我们的环境就是python3.9
python3.9本身不支持win10-

**Comment by LY-Xiang** [comment]
readme写一下吧

**Comment by model-err** [comment]
你即使把py脚本下下来，在win7也是跑不起来的.jpg
这个脚本好像就并不支持win10-

**Comment by LY-Xiang** [comment]
我们应该不会考虑win10-支持
因为py3.9没考虑

**Comment by model-err** [comment]
但是mzdyl应该在修了？
他似乎做了一个3.8.10的构建版本，但是没有用……

**Comment by LY-Xiang** [comment]
看情况吧
毕竟不同版本的功能/特性不同
如果向下兼容会很麻烦

**Comment by model-err** [comment]
mzdyl在头疼的修了.jpg
