### ISSUE TITLE
修补失败

### ISSUE THREAD

**Issue by MiunaQwQ** [Mzdyl/LiteLoaderQQNT_Install#107]
### 问题类型
请选择一个:
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
请填写您的运行版本:1.15

### 描述
简要描述您的问题:
运行QQ.exe报错

### 错误截图
请粘贴错误截图:
![图片](https://github.com/user-attachments/assets/7e6172cd-70f6-4159-aacd-0bf7ed3e4f1c)
![图片](https://github.com/user-attachments/assets/da765e88-8694-4bb6-9457-c00605f23e33)
![图片](https://github.com/user-attachments/assets/7241c04b-fd10-4f35-8a3d-c29bd2060a5a)

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by Mzdyl** [comment]
请尝试重装 https://github.com/adproqwq/LiteLoaderQQNT-CheckUpdateModule/releases 或依赖了 LiteLoaderQQNT-CheckUpdateModule 的插件
该报错可能是由于插件问题引起的
或者先移除数据目录的 plugins 文件夹，重装插件
