### ISSUE TITLE
windows修改了

### ISSUE THREAD

**Issue by Saber728Avalon** [Mzdyl/LiteLoaderQQNT_Install#108]
安装
找到 QQNT 安装目录，编辑 resources\app\app_launcher\index.js 文件，在最前端插入一行require(String.raw`此处为你 LiteLoaderQQNT 目录路径`);

javascript
require(String.raw`C:\LiteloaderQQNT`); // 此处换成你 LiteLoaderQQNT 目录位置
require('./launcher.node').load('external_index', module);

修改了  index.js，哪怕加个回车。启动qq就会报错 “文件已经损坏，请重新安装QQ”

**Comment by Mzdyl** [comment]
没有修补QQ
参考LL官网教程

**Comment by Mzdyl** [comment]
如果你使用了本软件仍出现此错误可能是使用过 dbghelp.dll 方案，且未更新 dbghelp.dll
因未提供截图无法提供更多帮助

**Comment by Saber728Avalon** [comment]
> 没有修补QQ 参考LL官网教程

谢谢，对QQ打了补丁就好了。
