### ISSUE TITLE
ntqq在27181中引入完整性检测，patch会存在问题

### ISSUE THREAD

**Issue by loyejaotdiqr47123** [Mzdyl/LiteLoaderQQNT_Install#111]
### 问题类型
请选择一个:
- [ ] Bug 反馈
- [ ] 功能改进
- [✓] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [✓] macOS
- [ ] Linux
- [ ] Windows

### 运行版本
27181

### 附加信息
ntqq:[https://dldir1.qq.com/qqfile/qq/QQNT/0ccac733/QQ9.9.15.27187_x64.exe](https://dldir1.qq.com/qqfile/qq/QQNT/0ccac733/QQ9.9.15.27187_x64.exe)

**Comment by Mzdyl** [comment]
之后我看看，这几天出门

**Comment by loyejaotdiqr47123** [comment]
> 之后我看看，这几天出门

27181是泄露的测试版，官方应该还没有发正式版

**Comment by Mzdyl** [comment]
该版本正常，刚刚测试完（

而且 完整性检测 去年就有了，安装器中的 patch_pe_file 就是用来 hook 检测的

**Comment by loyejaotdiqr47123** [comment]
你挂一会看看吧，听人说会喜提封号

**Comment by loyejaotdiqr47123** [comment]
![image](https://github.com/user-attachments/assets/f8329362-a57d-440b-947d-25697be39339)

**Comment by loyejaotdiqr47123** [comment]
![image](https://github.com/user-attachments/assets/cdaab97a-74d8-415a-9e86-702bdf56bd7c)
我这边也可以用，这个issue我就暂时关闭了

**Comment by loyejaotdiqr47123** [comment]
![image](https://github.com/user-attachments/assets/459e70ae-5291-4c50-a6e5-0b312df2e77b)
llonebot也有提醒，感觉应该是有问题吧

**Comment by LY-Xiang** [comment]
llqqnt有讨论
说是llob用了qq内部对象然后出的问题

**Comment by LY-Xiang** [comment]
tx加了完整性检查后一直没变
所以理论上llqqnt支持全部更新版本(

**Comment by loyejaotdiqr47123** [comment]
我挂几天看看

**Comment by Mzdyl** [comment]
llob/napcat 是 wrapper 的内部结构改了，暂不支持新版
和封号/ll本体 毫无关系也不影响
