### ISSUE TITLE
修补后无法启动

### ISSUE THREAD

**Issue by MinecraftSTL** [Mzdyl/LiteLoaderQQNT_Install#113]
### 问题类型
请选择一个:
- [x] Bug 反馈

### 运行平台
请选择您的运行平台:
- [x] Windows

### 运行版本
请填写您的运行版本:
    昨天更新的最新版本，由于我打不开，我看不到具体的版本号

### 描述
简要描述您的问题:
    修补后无法启动

### 错误截图
请粘贴错误截图:
     ![image](https://github.com/user-attachments/assets/182de8f9-5173-4399-980f-93ba10e2dc5f)

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:
    为更新后修补，显示修补成功

**Comment by LY-Xiang** [comment]
似乎是插件目录未设置好
尝试更改环境变量

**Comment by MinecraftSTL** [comment]
> 似乎是插件目录未设置好
> 尝试更改环境变量

你好，请问我需要如何更改哪一条

**Comment by MinecraftSTL** [comment]
> 首先检查llqqnt是否正确安装:C:\Program Files\Tencent\QQNT\resources\app\LiteLoaderQQNT-main是否存在 如果不存在 请重新安装llqqnt 如果存在 检查插件&数据目录的位置 然后设置环境变量LITELOADERQQNT_PROFILE为插件&数据目录

好的，已经成功运行，感谢你的耐心解答
