### ISSUE TITLE
Bug 反馈：不停"使用内嵌版本"

### ISSUE THREAD

**Issue by Huangsam04-github** [Mzdyl/LiteLoaderQQNT_Install#114]
### 问题类型
Bug 反馈

### 运行平台
Windows

### 运行版本
1.15

### 描述
在安装完LLQQNT之后会安装插件列表商店，但是一直在不停的循环，
最后报错退出，打开qq发现正常安装。

### 错误截图
![image](https://github.com/user-attachments/assets/1674188a-32bb-4544-ab2f-c168c83c6aa2)
![image](https://github.com/user-attachments/assets/bb88021e-5dc9-4742-8591-3e6e974d5f99)

### 附加信息
打开着代理软件，但是并未激活

**Comment by Mzdyl** [comment]
该bug在 0b626b8d4538425c932a5c1ca6c6aa6be6a7abf7 已修复，只是暂未更新到 release 中
