### ISSUE TITLE
前面步骤均无报错,打开QQ设置时闪退

### ISSUE THREAD

**Issue by 2108035037** [Mzdyl/LiteLoaderQQNT_Install#115]
- [ ] Bug 反馈

- [ ] Windows

QQNT 9.9.15-26909 (64位)

### 描述
前面步骤均无报错,打开QQ设置时闪退

### 错误截图
此错误无法截图

### 附加信息
实际上,安装过程中遇到很多bug,不过都是小问题,我通过提示,移动相应文件都解决了.我用的是第一种修补方法(下载dll文件至QQ.exe所在目录)

**Comment by LY-Xiang** [comment]
dll方式似乎在最新版本出问题了

**Comment by LY-Xiang** [comment]
请尝试重装QQ再用patcher修补

**Comment by 2108035037** [comment]
> 请尝试重装QQ再用patcher修补
![b42c549402305c4bf33e4212bf5134c](https://github.com/user-attachments/assets/3ecc8a9a-bf9a-4967-9c93-f15910f3673a)
![76199156780ed814542881771a15575](https://github.com/user-attachments/assets/b4dfb305-c444-48c3-8cda-ac6f28d6cdc1)
![a814030fddd50962be494247d80d62a](https://github.com/user-attachments/assets/70dbda5b-1ba8-4578-bd91-de07508b0b6b)

**Comment by 2108035037** [comment]
> 请尝试重装QQ再用patcher修补
![b42c549402305c4bf33e4212bf5134c](https://github.com/user-attachments/assets/3ecc8a9a-bf9a-4967-9c93-f15910f3673a)
![76199156780ed814542881771a15575](https://github.com/user-attachments/assets/b4dfb305-c444-48c3-8cda-ac6f28d6cdc1)
![a814030fddd50962be494247d80d62a](https://github.com/user-attachments/assets/70dbda5b-1ba8-4578-bd91-de07508b0b6b)

**Comment by LY-Xiang** [comment]
有没有重装
多次修补是不行的

**Comment by Mzdyl** [comment]
不太确定具体什么情况
尽量重装QQ后安装（

以及打开设置后闪退可能是 插件错误 之类的缘故
