### ISSUE TITLE
无法打开 QQ 并报错

### ISSUE THREAD

**Issue by Koitoouav** [Mzdyl/LiteLoaderQQNT_Install#117]
[](url)- [ ] Bug 反馈

- [x] Windows

请填写您的运行版本:9.9.15.27206

简要描述您的问题:使用一键包后无法打开 QQ。

![Snipaste_2024-08-21_08-15-48](https://github.com/user-attachments/assets/41783e3b-1947-4a5e-905e-5c86aca88133)

**Comment by hfsz2313** [comment]
插件问题
把目录里的插件删除重装

请尽量少使用中文目录 容易出现奇奇怪怪的问题（）
