### ISSUE TITLE
安装之后无法打开qq，缺失plugins目录

### ISSUE THREAD

**Issue by reserveword** [Mzdyl/LiteLoaderQQNT_Install#121]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
*请填写您的运行版本:*
1.15

### 描述
*简要描述您的问题:*
安装之后无法打开qq

### 错误截图
*请粘贴错误截图:*
![图片](https://github.com/user-attachments/assets/0135040f-e3b6-4579-a9a6-fb8c1617aa4a)

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*
看起来安装的时候没有新建对应的目录
检查LiteloaderQQNT文件夹发现确实没有plugins目录

**Comment by Mzdyl** [comment]
若想使用的话请先自行创建 plugins 文件夹
此 bug 将在后续版本修复（ 理论上plugins 文件夹应该由LL 自动创建，不过可能LL 改了逻辑，这边没做对应修改）
