### ISSUE TITLE
[feat]：修改README中 下载执行脚本的命令

### ISSUE THREAD

**Issue by Jackhr-arch** [Mzdyl/LiteLoaderQQNT_Install#122]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [ ] Bug 反馈
- [x] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [x] Linux
- [ ] Windows

### 描述
*简要描述您的问题:*
你可以把[README](https://github.com/Mzdyl/LiteLoaderQQNT_Install/blob/main/README.md?plain=1#L20)中
```bash
curl -L "https://github.com/Mzdyl/LiteLoaderQQNT_Install/releases/latest/download/install.sh" -o /tmp/install_stable.sh && bash /tmp/install_stable.sh
```
改成 
```bash
curl -L "https://github.com/Mzdyl/LiteLoaderQQNT_Install/releases/latest/download/install.sh" | bash
```

> 命令一长，MarkDown的行内代码简直不能看

### 顺便
建议在申请su权限前先向用户解释一下，在翻阅代码时我似乎没有见到需要提权的操作

**Comment by Mzdyl** [comment]
最开始就是用的 curl -L XXX  | bash ，后来因为尝试做多shell适配还是啥情况改来改去最后变成了现在这样
不过到目前版本来说  curl -L XXX  | bash 确实可行且方便，抽空就改

以及 申请su权限 解释，后续会加，不过估计会比较慢，最近开学了课表早八排到了晚八😱
