### ISSUE TITLE
Weird messages

### ISSUE THREAD

**Issue by clzls** [Mzdyl/LiteLoaderQQNT_Install#123]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
*请填写您的运行版本:*
1.15

### 描述
*简要描述您的问题:*
反复输出大量“使用内嵌版本”并报错 `maximum recursion depth exceeded while calling a Python object`.
像是没有识别到代理后网络连接失败引起的？但是该提示令人迷惑。

### 错误截图
*请粘贴错误截图:*
![微信截图_20240831010204](https://github.com/user-attachments/assets/a6758b46-3388-4f7a-a872-6d1f8194f973)

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*

**Comment by clzls** [comment]
Update: 猜测是 Watt 加速器的代理证书不受自带 SSL 证书库的软件认可，导致进入了[install_windows.py:583](https://github.com/Mzdyl/LiteLoaderQQNT_Install/blob/3da095d10a27045ba5b70f4fa2383f0997d5b835/install_windows.py#L583)，不过不太明白为什么这句话反复被触发……

**Comment by LY-Xiang** [comment]
该问题在
[d4694595efd26995d0803497893959a633a90d62](https://github.com/Mzdyl/LiteLoaderQQNT_Install/commit/d4694595efd26995d0803497893959a633a90d62)
已经修复
请尝试1.16(pre)或者最新action打包版本

**Comment by Mzdyl** [comment]
之前修复了，预发布后忘改正式发布了（逃

**Comment by LY-Xiang** [comment]
> 之前修复了，预发布后忘改正式发布了（逃

😰
