### ISSUE TITLE
修改index.js后无法打开qq

### ISSUE THREAD

**Issue by Iansniper** [Mzdyl/LiteLoaderQQNT_Install#124]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
*请填写您的运行版本:*
QQNT 9.9.7-21484
LiteLoader 1.16

### 描述
*简要描述您的问题:*
根据安装指南，在QQNT\resources\app\app_launcher目录下将其中的index.js进行了修改
但是修改之后，一旦打开QQ，就不显示任何按钮，完全无法登录，将index.js改回原样就会恢复正常，因而无法使用LiteLoader

### 错误截图
*请粘贴错误截图:*

![image](https://github.com/user-attachments/assets/21acea42-cddf-4b87-a2aa-9ecf642749c4)
修改index.js之后的QQNT登录界面

![7d86a2c0ac2562bc62c160f8030e87d2](https://github.com/user-attachments/assets/8f6d43ea-351f-452c-9ca9-36de11cd259b)
修改的index.js内容

![image](https://github.com/user-attachments/assets/4bf26dc0-6783-4967-826c-2666ea85d848)
LiteLoader本体目录的情况

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*
已经在QQNT目录下安装了dbghelp.dll以防止完整性验证，但还是不行，系统为x64

**Comment by Mzdyl** [comment]
此 bug 为 ll 1.2.x 版本与 QQ 热更新有冲突
可选方案有暂用1.2.0之前的版本，或者重装QQ，避免热更新（不损失数据）
