### ISSUE TITLE
命令行安装成功后打不开QQ

### ISSUE THREAD

**Issue by dakezuo** [Mzdyl/LiteLoaderQQNT_Install#128]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [ ✔️] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [✔️ ] macOS
- [ ] Linux
- [ ] Windows

### 运行版本
*请填写您的运行版本:*

### 描述
*简要描述您的问题:*
给与终端磁盘权限后，安装成功后QQ无法打开，报错

### 错误截图
*请粘贴错误截图:*
<img width="520" alt="image" src="https://github.com/user-attachments/assets/079c1447-0552-4f00-8d10-09ecb16169a0">

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*

**Comment by Mzdyl** [comment]
插件问题，检查是否安装了需要依赖的插件
或者先临时全部移除插件

**Comment by EsunR** [comment]
重新安装了最新版的 QQ 解决了
