### ISSUE TITLE
[功能改进] QQNT 28060需要修改的index.js已被移除

### ISSUE THREAD

**Issue by abbaccadd0** [Mzdyl/LiteLoaderQQNT_Install#130]
### 问题类型
- [ ] Bug 反馈
- [x] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
1.16 Nuitka ver.

### 描述
无法用于QQNT 9.9.15-28060，需要修改的index.js被移除
框架本体已提交issue并且似乎已经适配
安装程序可能对于QQ版本需要做出判断和修改

### 错误截图
![Snipaste_2024-09-14_20-47-46](https://github.com/user-attachments/assets/051eb329-d3b7-4787-9b26-f7ce7267b895)

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
[框架那边的issue](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/417#issuecomment-2350954530)

**Comment by himetuki** [comment]
开始修补 index.js…
已将旧版文件备份为 index.js.bak
修补 index.js 时发生错误: [Errno 2] No such file or directory: 'D:\\……………………\\index.js'
我也出现了这个问题<img src="https://bbs-static.miyoushe.com/static/2024/07/31/cd2ca0d9143e10e588e0a0191bf71c3b_5335236511308035335.png" alt="素裳 喷火" width="75" >

**Comment by laiyoi** [comment]
只是改了路径，但是修改后没有用
![image](https://github.com/user-attachments/assets/357d7050-0384-4911-ba06-997c2f19b95c)

**Comment by Mzdyl** [comment]
28060 需要改的有点多
先修改 package.json 在修改 version 内的 index.js
且存在其他问题，建议先用旧版（

有想研究的也可以参考 eb1eca8d409dc6e7aed35e4fb2a8e23b1eb13e15

**Comment by Mzdyl** [comment]
https://github.com/Mzdyl/LiteLoaderQQNT_Install/releases/tag/pre1.17

可以试试，有 bug 请反馈
使用方法参考说明

**Comment by madman43** [comment]
目前9.9.15-28131 (64位) 使用1.17版本更新好像没啥问题，我没有使用LaunchQQ.exe来启动，使用1.17版本之前用了1.16版本修复，不知道是不是这个原因
![image](https://github.com/user-attachments/assets/d6c8c34e-5493-4685-9da5-89daede03ff0)
