### ISSUE TITLE
出现异常错误

### ISSUE THREAD

**Issue by Starrain08** [Mzdyl/LiteLoaderQQNT_Install#132]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
*请填写您的运行版本:*
 9.9.15-28131 (64位)

### 描述
*简要描述您的问题:*
正常安装后，在安装其他插件重启后报错，无论是采用手动还在自动安装

### 错误截图
*请粘贴错误截图:*
![image](https://github.com/user-attachments/assets/a23c6c0f-d85b-46fd-b1ad-f0ccd2996b46)

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*

已安装插件
![image](https://github.com/user-attachments/assets/298b81f7-32ae-412c-90a3-376347b56bd2)

**Comment by Violiate** [comment]
> 问题找到了，某些插件不适合新版本部署方法，会导致崩溃

刚刚重新部署后，一崩溃来找办法就看到这个了

**Comment by Violiate** [comment]
> 问题找到了，某些插件不适合新版本部署方法，会导致崩溃

上面图片里的点击确定后，会出现一个新的弹窗“插件缺少依赖 euphony”
