### ISSUE TITLE
28131貌似已经不需要通过LaunchQQ启动

### ISSUE THREAD

**Issue by kafan-BangBangTuan** [Mzdyl/LiteLoaderQQNT_Install#133]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [ ] Bug 反馈
- [ ] 功能改进
- [x` ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x` ] Windows

### 运行版本
*请填写您的运行版本:*
28131

### 描述
*简要描述您的问题:*
貌似已经不需要通过LaunchQQ启动，可以直接启动并正常使用

### 错误截图
*请粘贴错误截图:*

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*
https://dldir1.qq.com/qqfile/qq/QQNT/Windows/QQ_9.9.15_240919_x64_01.exe

**Comment by kafan-BangBangTuan** [comment]
> ### 问题类型
> _请选择一个:`将所选择的对应选项前方括号内空格改为x`_
> 
> * [ ]  Bug 反馈
> * [ ]  功能改进
> * [x] 其他
> * [ ]  与作者吹水（bushi
> 
> ### 运行平台
> _请选择您的运行平台:_
> 
> * [ ]  macOS
> * [ ]  Linux
> * [x] Windows
> 
> ### 运行版本
> _请填写您的运行版本:_ 28131
> 
> ### 描述
> _简要描述您的问题:_ 貌似已经不需要通过LaunchQQ启动，可以直接启动并正常使用
> 
> ### 错误截图
> _请粘贴错误截图:_
> 
> > _若为 Bug 反馈且附带截图将被优先解决_
> 
> ### 附加信息
> _如果有任何其他相关信息，请注明:_ https://dldir1.qq.com/qqfile/qq/QQNT/Windows/QQ_9.9.15_240919_x64_01.exe

**Comment by Mzdyl** [comment]
release 说明写了啊，install_windows_next 无需 launchQQ 启动
launchQQ 本来就是一个过渡（
