### ISSUE TITLE
【bug】 QQNT28060/28131在使用Install_Next安装成功后出现部分功能不可用的情况

### ISSUE THREAD

**Issue by LeoChen98** [Mzdyl/LiteLoaderQQNT_Install#134]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
*请填写您的运行版本:* install_windows_Next

### 描述
*简要描述您的问题:* 安装成功后以下功能不可用或异常：

* QQ自带截图：无法正确显示覆盖层，鼠标单击后闪退。
* 消息列表： 预览消息不显示，见下图红圈部分：
![image](https://github.com/user-attachments/assets/9b04246e-42df-4dab-94c7-46a6488ad319)

### 错误截图
*请粘贴错误截图:*见描述中图

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*
可能有用的信息：
![image](https://github.com/user-attachments/assets/e59d12e0-641f-4f7c-912a-63376e822ebf)
![image](https://github.com/user-attachments/assets/9ae17b53-3645-4c59-844c-edcb9535c268)
![image](https://github.com/user-attachments/assets/cc3dbedd-9451-4300-8c45-7c5cfbcbfe40)

**Comment by LeoChen98** [comment]
18060和18131两个版本中该问题表现一致

**Comment by LeoChen98** [comment]
目前消息预览的问题已通过禁用LLAPI依赖解决，建议下个版本的Install过程中自动检测LLAPI并禁用。（但该操作对其他插件的影响未知，目前暂未发现由禁用LLAPI引起的其他插件的异常）

**Comment by LY-Xiang** [comment]
我们不处理插件对于新版llqqnt的兼容 只是安装
llapi过了八个月没动静 也不能要求它新版兼容

**Comment by LeoChen98** [comment]
> 我们不处理插件对于新版llqqnt的兼容 只是安装 llapi过了八个月没动静 也不能要求它新版兼容

所以说建议先把他禁用了(

**Comment by Mzdyl** [comment]
LLAPI 是用户自行安装的
这个项目仅仅负责安装 LiteloaderQQNT 以及 提供有限的提供插件商店 附加安装
并不对插件问题负责（

以及LLAPI 不已经死了好久了吗，代码删了，作者不维护了，为啥还会有残留啊（🤯
现在也没有其他插件依赖LLAPI，目前来说 LLAPI 只有害无益
