### ISSUE TITLE
QQ以管理员模式运行，导致不可拖入文件

### ISSUE THREAD

**Issue by singularity2000** [Mzdyl/LiteLoaderQQNT_Install#136]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
*请填写您的运行版本:28060*

### 描述
*简要描述您的问题:*
使用此工具后，QQ以管理员模式运行，无法从文件资源管理器拖入文件，光标显示为禁止符号。我因为安装了转换本地音频为语音的插件，不得不使用拖入功能。想知道简便的解决方法，如果可以修改代码，或免去管理员模式就好了。

### 错误截图
*请粘贴错误截图:*

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*

**Comment by Mzdyl** [comment]
本软件仅在修补过程需要管理员权限
运行 QQ 并不需要管理员权限，请检查其他原因问题，比如 dll 的自动修复可能需要管理员权限 等

**Comment by WJZ-P** [comment]
这是Windows系统中存在的一个bug，其他软件也会出现这个情况。
