### ISSUE TITLE
MAC安装插件无效

### ISSUE THREAD

**Issue by marcozyj** [Mzdyl/LiteLoaderQQNT_Install#137]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [x] macOS
- [ ] Linux
- [ ] Windows

### 运行版本
*请填写您的运行版本:*
6.9.55-28172

### 描述
*简要描述您的问题:*
mac用脚本安装完后，打开qq设置不会显示插件

### 错误截图
*请粘贴错误截图:*
<img width="888" alt="log" src="https://github.com/user-attachments/assets/ccaf0850-03a5-4aeb-be15-6a932952bd31">

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*

**Comment by Mzdyl** [comment]
第一：
<img width="834" alt="截屏2024-09-24 16 26 33" src="https://github.com/user-attachments/assets/5e36743d-31e9-4b82-90bc-c28f7baf4319">
第二：28060+ 版本mac没适配，等 liteloaderQQNT 本体更新适配 mac

**Comment by marcozyj** [comment]
> 第一： <img alt="截屏2024-09-24 16 26 33" width="834" src="https://private-user-images.githubusercontent.com/25149539/370198588-5e36743d-31e9-4b82-90bc-c28f7baf4319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjgwNjMsIm5iZiI6MTcyNzE2Nzc2MywicGF0aCI6Ii8yNTE0OTUzOS8zNzAxOTg1ODgtNWUzNjc0M2QtMzFlOS00YjgyLTkwYmMtYzI4ZjdiYWY0MzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA4NDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMDdmMzJiMTMyN2E3NmZmNDRiNTMxMDI0NjFiYzQ2NTIxY2RjZWZmZGQ1MGRmNWU5MTMxNTYxMGFmOWNiYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zsvkwuGl57EhMDS666y8rIrylF2a7gfp-kbvea7issc"> 第二：28060+ 版本mac没适配，等 liteloaderQQNT 本体更新适配 mac

好的，谢谢
