### ISSUE TITLE
下载界面卡住

### ISSUE THREAD

**Issue by madman43** [Mzdyl/LiteLoaderQQNT_Install#138]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
*请填写您的运行版本:*
QQ 28131版本
修改程序1.17版本

### 描述
*简要描述您的问题:*
下载界面卡很久

### 错误截图
*请粘贴错误截图:*
![image](https://github.com/user-attachments/assets/5b9da023-2b5d-4d79-b661-8977a9023eca)

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*

**Comment by Mzdyl** [comment]
重新运行试试吧（或者开关代理
这个是脚本通过 requests 发现能直接连接 github
然后进行下载，但可能网络是能访问 github 但速度过慢之类的导致卡住

之后将在脚本中添加 下载超时检测，现在还请重新运行

**Comment by madman43** [comment]
> 重新运行试试吧（或者开关代理 这个是脚本通过 requests 发现能直接连接 github 然后进行下载，但可能网络是能访问 github 但速度过慢之类的导致卡住
> 
> 之后将在脚本中添加 下载超时检测，现在还请重新运行

确实经常卡住，只能重新试试

**Comment by Mzdyl** [comment]
e1853e5999ffb4bc908a153be28183640b83eb61 中已经添加超时检测及超时使用代理再次下载
