### ISSUE TITLE
安装过旧版本LiteLoader升级安装时检测到dbghelper.dll跳过修补导致dbghelper.dll版本不兼容

### ISSUE THREAD

**Issue by schalkiii** [Mzdyl/LiteLoaderQQNT_Install#139]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [ ] Bug 反馈
- [x] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
1.17

### 描述
*简要描述您的问题:*
安装过旧版本LiteLoader升级安装时检测到dbghelper.dll便跳过修补，会使得无法更新至最新的dbghelper.dll，进而dbghelper.dll与QQNT版本不兼容。

### 错误截图
![image](https://github.com/user-attachments/assets/2bb09334-261a-45cb-9df8-f819cdc8b34f)
> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*

**Comment by LY-Xiang** [comment]
该脚本采用的修补不是DLLhijacker而是patcher
请自行更新dll或删除dll并重装上阵QQ以使用脚本

**Comment by Mzdyl** [comment]
dbghelper.dll 没有版本号信息，无法实现检查dbghelper.dll 是否最新，问题关闭
使用 dbghelper.dll 的只能自己管理版本，或者直接使用脚本的自动 patcher 方案
