### ISSUE TITLE
使用启动器更新版本时 启动器json文件修补路径出现问题

### ISSUE THREAD

**Issue by FridayAnubis** [Mzdyl/LiteLoaderQQNT_Install#140]
### 问题类型
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
**1.17**

### 描述
更新版本时 `package.json` 和 `index.json` 修补路径出现问题
安装器无报错

以package.json为例

理想情况：
`"main": "./app_launcher/index.js"`

实际上修补之后的字段：
`"main": "./application/app_launcher/index.js"`

`index.json`中同理。我不确定这个写法是否有特殊占位符的含义，但我用安装器将**正常使用的** _Liteloader_ **1.21** 更新至 **1.22** 之后无法加载，手动将两个json文件修改并重新指定 _Liteloader_ 路径后加载新版本框架成功。

### 相关截图
![image](https://github.com/user-attachments/assets/c33a9b2e-1397-4e08-b091-fa0c2439e7e7)

**Comment by Mzdyl** [comment]
不太能理解你说的情况
安装器运行后会将package.json 的 main字段 = "./app_launcher/ml_install.js"
而你所述的 "main": "./application/app_launcher/index.js" 是未修改的情况，即原始 QQ 的 main 字段
以及安装器不会对新版QQ修改 index.json 文件，而是通过创建 ml_install.js 加载 LiteloaderQQNT

你的情况我认为更大概率是 QQ 发生了热更新，导致修补的文件全被复原了

**Comment by FridayAnubis** [comment]
但这个问题的触发时机是使用安装器更新版本的时候——
在这之前是通过插件屏蔽更新的，巧合吗？

**Comment by Mzdyl** [comment]
无法复现，提供下安装器的运行截图以及运行的 qq 的版本号，
安装器只会对QQ内最新的version 进行修补，不确定屏蔽更新插件是如何实现的
可能会导致修补的 version 和启动的 version 不一致

**Comment by FridayAnubis** [comment]
我询问了一些其他用户，似乎只有我出现这个问题，虽然我这边是稳定出现。QQ版本 _9.9.15-28131_ 。
确实不是一个普遍性的问题，可能与我环境配置有关，抱歉打扰 :)
如果没什么其他需要我提供的信息您可以Close issue了

**Comment by Mzdyl** [comment]
这个问题目前无法复现，也没有其他人反馈相同遭遇，暂时无法解决
不过若能提供安装器运行截图的话可能方便排查

若暂时无法提供的话就只能先关闭问题，若再有其他人遇到类似情况再重新打开

**Comment by FridayAnubis** [comment]
好的，那我这边先关闭了。之后下个版本若还有相似问题再开
