### ISSUE TITLE
A JavaScript error occurred in the mainprocess

### ISSUE THREAD

**Issue by Bei-Chen-Leo** [Mzdyl/LiteLoaderQQNT_Install#141]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
*请填写您的运行版本:*
安装器1.17
NTQQ版本QQ_9.9.15_240927_x64_01
### 描述
*简要描述您的问题:*

A JavaScript error occurred in the mainprocess
### 错误截图
*请粘贴错误截图:*
![image](https://github.com/user-attachments/assets/4c4c2cfb-9685-4d19-a058-0fe7d304c3fb)

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*

**Comment by Mzdyl** [comment]
插件问题，自动发送消息插件出错了，重装该插件或者移除该插件
