### ISSUE TITLE
Windows server 2019下频繁安装失败

### ISSUE THREAD

**Issue by ReSatori** [Mzdyl/LiteLoaderQQNT_Install#145]
### 问题类型
- [X] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
- [ ] macOS
- [ ] Linux
- [X] Windows

### 运行版本
*1.17*

### 描述
*Windows server 2019下频繁安装失败，网络环境为美国，疑似文件权限问题*

### 错误截图
![%7NTSMMXRX{(SM5J6}`D6I8](https://github.com/user-attachments/assets/504bc106-af14-4b40-9030-58bd9a878f68)

![~~HXC3TY((9}Y1O~C@O%`F6](https://github.com/user-attachments/assets/1377d9c2-af61-45ee-acf2-906ff4b8da09)

### 附加信息
*如果有任何其他相关信息，请注明:*

**Comment by byx2020** [comment]
同样遇到了此问题，简单按照手动安装的流程操作检查了一下，发现是文件没有被放到正确的位置，
解决方案为将LiteLoaderQQNT.zip解压出来的文件夹手动放到“C:\Program Files\Tencent\QQNT\resources\app\LiteLoaderQQNT”这个路径里面即可

**Comment by ReSatori** [comment]
> 同样遇到了此问题，简单按照手动安装的流程操作检查了一下，发现是文件没有被放到正确的位置， 解决方案为将LiteLoaderQQNT.zip解压出来的文件夹手动放到“C:\Program Files\Tencent\QQNT\resources\app\LiteLoaderQQNT”这个路径里面即可

谢谢~！我去试试

**Comment by ReSatori** [comment]
> 网络错误，emmm 开梯子了？ssl 错误有可能因为梯子节点质量一般导致的

没有，本身就是美国的服务器没必要开
按照[byx2020](https://github.com/byx2020)的方法解决了QWQ
