### ISSUE TITLE
程序安装完成之后启动qq弹出报错窗口

### ISSUE THREAD

**Issue by Faxmell** [Mzdyl/LiteLoaderQQNT_Install#146]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x ] Windows

### 运行版本
*请填写您的运行版本:*
1.17

### 描述
*简要描述您的问题:*
运行完安装程序之后打开qq就只弹出这个窗口，我不太清楚是不是我的问题

### 错误截图
*请粘贴错误截图:*
![屏幕截图 2024-10-17 150534](https://github.com/user-attachments/assets/241e28e7-0873-48a6-89fc-c48d20088960)

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*
抱歉我不太确定自己这个算不算bug反馈

**Comment by Mzdyl** [comment]
啊这，
可能是最近版本下载逻辑有点问题，一会我修修，

先临时手动将 LiteLoaderQQNT.zip 解压出来的文件夹手动放到“D:\Tencent\resources\app\LiteLoaderQQNT”这个路径里面即可即可使用

**Comment by TNXG** [comment]
> 啊这， 可能是最近版本下载逻辑有点问题，一会我修修，
> 
> 先临时手动将 LiteLoaderQQNT.zip 解压出来的文件夹手动放到“D:\Tencent\resources\app\LiteLoaderQQNT”这个路径里面即可即可使用

![image](https://github.com/user-attachments/assets/f876c49b-1a40-4bc0-9634-713c12680a06)

**Comment by Mzdyl** [comment]
> > 啊这，可能是最近版本下载逻辑有点问题，我会修改一下，
> > 先临时手动将LiteLoaderQQNT.zip解压出来的文件夹手动放到“D:\Tencent\resources\app\LiteLoaderQQNT”这个路径里面就可以使用
> 
> ![图像](https://private-user-images.githubusercontent.com/69001561/377486630-f876c49b-1a40-4bc0-9634-713c12680a06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzUwOTUsIm5iZiI6MTcyOTE3NDc5NSwicGF0aCI6Ii82OTAwMTU2MS8zNzc0ODY2MzAtZjg3NmM0OWItMWE0MC00YmMwLTk2MzQtNzEzYzEyNjgwYTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE0MTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YWJiZDNiODNlMTdhNGFjMGMyZDA3MmU3MzI0MjFhNTBhYjM3YWFmNjcwZWE5NDk2ZTYxZTYyMmUyMjNiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cQL8-AFFerxIbl-g844C2N1dpLx9QgEuKdGnWKtxMas)

这个是你安装的插件有问题，看样子是markdown？插件

**Comment by Faxmell** [comment]
> > > 啊这，可能是最近版本下载逻辑有点问题，我会修改一下，
> > > 先临时手动将LiteLoaderQQNT.zip解压出来的文件夹手动放到“D:\Tencent\resources\app\LiteLoaderQQNT”这个路径里面就可以使用
> > 
> > 
> > ![图像](https://private-user-images.githubusercontent.com/69001561/377486630-f876c49b-1a40-4bc0-9634-713c12680a06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzUwOTUsIm5iZiI6MTcyOTE3NDc5NSwicGF0aCI6Ii82OTAwMTU2MS8zNzc0ODY2MzAtZjg3NmM0OWItMWE0MC00YmMwLTk2MzQtNzEzYzEyNjgwYTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE0MTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YWJiZDNiODNlMTdhNGFjMGMyZDA3MmU3MzI0MjFhNTBhYjM3YWFmNjcwZWE5NDk2ZTYxZTYyMmUyMjNiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cQL8-AFFerxIbl-g844C2N1dpLx9QgEuKdGnWKtxMas)
> 
> 这个是你安装的插件有问题，看样子是markdown？插件

我第一次用，还没安装过什么插件

**Comment by Mzdyl** [comment]
那看一下用户下的documents文件夹，里面的liteloaderqqnt 文件夹的plugins 是否有东西
全新安装的话应该只有一个list-view
删掉不应该存在的看看

**Comment by TNXG** [comment]
> 那看一下用户下的documents文件夹，里面的liteloaderqqnt 文件夹的plugins 是否有东西
> 全新安装的话应该只有一个list-view
> 删掉不应该存在的看看

我已经解决了相关问题，蟹蟹佬
