### ISSUE TITLE
安装完后LiteLoaderQQNT不是最新版

### ISSUE THREAD

**Issue by 2584191127** [Mzdyl/LiteLoaderQQNT_Install#148]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
1.17

### 描述
安装完后LiteLoaderQQNT不是最新版

### 错误截图
![image](https://github.com/user-attachments/assets/60bdc533-6aea-40ea-9540-4b1f5c01186b)

**Comment by LY-Xiang** [comment]
可能是由于github文件下载失败所以fallback到内嵌版本

**Comment by Mzdyl** [comment]
1.2.0 + 最低兼容 25765

虽然这个和安装的不是最新版本没啥关系（逃

**Comment by 2584191127** [comment]
更新了QQ后再重新安装就好了（tmd更新的QQ给我安装到c盘去了）
