### ISSUE TITLE
脚本运行报错

### ISSUE THREAD

**Issue by wentlwr** [Mzdyl/LiteLoaderQQNT_Install#150]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x ] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [ ] Linux
- [x ] Windows

### 运行版本
*请填写您的运行版本:windows 10 LTSC

### 描述
*简要描述您的问题:脚本运行时报错，打开QQ 也报错

### 错误截图
![image](https://github.com/user-attachments/assets/0b12df3b-8d3d-4253-a708-dfe81449645c)
![image](https://github.com/user-attachments/assets/f4e883e0-1b2b-449f-a54a-50ca5ece702a)

**Comment by Mzdyl** [comment]
https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/11424777239/artifacts/2078831587

请先使用这一版本，这一版本修复了网络差环境下的离线安装（
