### ISSUE TITLE
插件商店 move后 目录名称不一致

### ISSUE THREAD

**Issue by taomi** [Mzdyl/LiteLoaderQQNT_Install#16]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/1817451/ed360aad-9b90-4471-ade3-57b9115451d7)

**Comment by Mzdyl** [comment]
这个是输出显示问题，并不影响实际使用（那两条 moving 显示是为了方便确定目录加上的，实际移动的是git 文件的原始名称
不过也确实算是个小 bug ，等抽空修了

**Comment by taomi** [comment]
问题不大 ，摸熟了，都正常用
