### ISSUE TITLE
Appimage版本能否像install.sh那样加入一键插件安装器

### ISSUE THREAD

**Issue by LFRon** [Mzdyl/LiteLoaderQQNT_Install#161]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [ ] Bug 反馈
- [x ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [x ] Linux
- [ ] Windows

### 运行版本
*请填写您的运行版本:https://github.com/Mzdyl/LiteLoaderQQNT_Install/releases/download/1.18.1/QQ.AppImage
用的这个版本

### 描述
*简要描述您的问题:*能否像Linux的install.sh执行后那样加入在线插件安装器

### 错误截图
*请粘贴错误截图:*

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*

**Comment by Mzdyl** [comment]
仓库中的 repack_appimage.sh 就是
将QQ.Appimage 和脚本放同一目录 运行即可（

**Comment by LFRon** [comment]
> 仓库中的 repack_appimage.sh 就是 将QQ.Appimage 和脚本放同一目录 运行即可（

哦哦好的,谢谢大佬!
