### ISSUE TITLE
使用其他Flatpak封装腾讯系软件会导致系统内QQ被错误检测。

### ISSUE THREAD

**Issue by MuTong233** [Mzdyl/LiteLoaderQQNT_Install#162]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [x] Linux
- [ ] Windows

### 运行版本
*请填写您的运行版本:*
Ubuntu 24.04.1 LTS
linuxqq/now 3.2.12-28418 amd64 [已安装，本地]

### 描述
*简要描述您的问题:*
在Flatpak安装了QQ音乐时（或其他腾讯系软件）会错误检测成Flatpak版。

### 错误截图
*请粘贴错误截图:*
检测到 Flatpak 版 QQ 已安装
正在拉取最新Release版本的仓库
通过GitHub获取最新Release版本
错误： com.qq.QQ/*unspecified*/*unspecified* 未安装

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*

**Comment by Mzdyl** [comment]
之前包名判断写太宽松了，马上改
