### ISSUE TITLE
Error reading registry key: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by Shingura** [Mzdyl/LiteLoaderQQNT_Install#17]
OS: Windows 11 专业版 22H2/22621.2283

无论是否以管理员身份运行均输出：
```
Error reading registry key: [WinError 2] 系统找不到指定的文件。
An error occurred: 'NoneType' object has no attribute 'replace'
Press Enter to exit.
```

**Comment by Mzdyl** [comment]
请问是不是安装后移动了QQ 的位置了
如果是的话请先使用 [1.1版本](https://github.com/Mzdyl/LiteLoaderQQNT_Install/releases/download/1.1/install_windows.exe)选择QQ.exe文件安装（此版本需要自行安装应用商店
该问题已经修复，暂时还未更新，请先临时使用旧版安装
