### ISSUE TITLE
发生错误: HTTPSConnectionPool

### ISSUE THREAD

**Issue by G-Cutemon** [Mzdyl/LiteLoaderQQNT_Install#18]
发生错误: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Mzdyl/LiteLoaderQQNT_Install/releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

**Comment by Mzdyl** [comment]
啊这，看样子是检测更新时连接 Github 发生错误
不过脚本中检查更新错误应该不影响整体安装使用

**Comment by G-Cutemon** [comment]
> 啊这，看样子是检测更新时连接 Github 发生错误 不过脚本中检查更新错误应该不影响整体安装使用

打开直接就按任意键退出了，感觉不能往下跑了……qwq

**Comment by Mzdyl** [comment]
坏诶，我一会看看修修

**Comment by G-Cutemon** [comment]
> 修好了，检查更新发生错误不会影响后续安装，请尝试下面的版本 https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/7917953034/artifacts/1248306297 （因为还打算修改些其他地方，所以先不作为正式版发布

好的！感谢~
