### ISSUE TITLE
Deepin Linux 玲珑打包的QQ问题

### ISSUE THREAD

**Issue by 8MiYile** [Mzdyl/LiteLoaderQQNT_Install#184]
### 问题类型
*请选择一个:`将所选择的对应选项前方括号内空格改为x`*
- [ ] Bug 反馈
- [X] 功能改进
- [ ] 其他
- [X] 与作者吹水（bushi

### 运行平台
*请选择您的运行平台:*
- [ ] macOS
- [X] Linux
- [ ] Windows

### 运行版本
*请填写您的运行版本:*
Deepin Linux 23
6.6.59-amd64-desktop-hwe

### 描述
*简要描述您的问题:*
我电脑的QQ是通过应用商店下载的玲珑打包的QQ 感觉好像是因为玲珑打包的应用和原版的路径不一样 导致安装后没效果 希望能支持一下

### 错误截图
*请粘贴错误截图:*

> *若为 Bug 反馈且附带截图将被优先解决*

### 附加信息
*如果有任何其他相关信息，请注明:*

**Comment by Mzdyl** [comment]
后续应该会添加支持，不过大概不会太快，玲珑还没了解过，可能会之后适配

**Comment by jbwfu** [comment]
@8MiYile  玲珑实际运行的是一个容器，配置默认在 `$HOME/.linglong`，变量传递暂不清楚，以下命令可用
QQ_PATH 具体路径根据情况修改版本

```sh
mkdir -p "$HOME/.linglong/linux.qq.com.linyaps/share/LiteLoaderQQNT"
QQ_PATH=/var/lib/linglong/layers/main/linux.qq.com.linyaps/3.2.15.30484/x86_64/binary/files tmp="$HOME/.linglong/linux.qq.com.linyaps/share/LiteLoaderQQNT" bash install.sh --ll-dir="$_tmp" --ll-profile="$_tmp"
```
