### ISSUE TITLE
注册表读取失败: [WinError 2] 系统找不到指定的文件

### ISSUE THREAD

**Issue by bandengzex** [Mzdyl/LiteLoaderQQNT_Install#24]
这个是我系统的错误么，官方教程安装也是QQ其他是文件损坏
已经管理员启动了
```
当前已是最新版本，开始安装。
注册表读取失败: [WinError 2] 系统找不到指定的文件。
发生错误: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by Mzdyl** [comment]
这是因为你的 QQ 安装并没有写入系统注册表，导致无法读取
可以重装一下 QQ 或者使用[1.1版本](https://github.com/Mzdyl/LiteLoaderQQNT_Install/releases/download/1.1/install_windows.exe)选择QQ.exe文件安装，不过旧版不回同步安装应用商店

**Comment by Mzdyl** [comment]
如果可以请尝试以下测试版
[Actions](https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/8182009273/artifacts/1304425253)
不过由于你所述的  `官方教程安装也是QQ其他是文件损坏`，所以不确保是否仍存在其他问题，如果还有问题，请提供更详细的截图

**Comment by yuhao7370** [comment]
> 如果可以请尝试以下测试版 [Actions](https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/8182009273/artifacts/1304425253) 不过由于你所述的 `官方教程安装也是QQ其他是文件损坏`，所以不确保是否仍存在其他问题，如果还有问题，请提供更详细的截图

<img width="740" alt="bug1" src="https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/53969724/807b8c49-280e-4e93-b40a-af90c017e0aa">
出现了相同的错误，使用测试版编码报错

**Comment by Mzdyl** [comment]
> > 如果可以请尝试以下测试版本[操作](https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/8182009273/artifacts/1304425253)但由于您所述的`官方教程安装也是QQ其他是文件损坏`，所以不确定是否仍然存在其他问题，如果还存在问题，请提供更详细的截图
> 
> <img alt="错误1" width="740" src="https://private-user-images.githubusercontent.com/53969724/311943369-807b8c49-280e-4e93-b40a-af90c017e0aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDA4MTMsIm5iZiI6MTcxMDMwMDUxMywicGF0aCI6Ii81Mzk2OTcyNC8zMTE5NDMzNjktODA3YjhjNDktMjgwZS00ZTkzLWI0MGEtYWY5MGMwMTdlMGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAzMjgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYzdiZTI3ZDc2YzE0OTU1ZGUzMTAyZTVkMTk0ZjVmZGE4Y2EzMjAwNzc5N2E5MTllNjY5MmVhZDFhODNlMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._uAuQFgGI0X_ST89XRVJpArXtT_jwquoIKVtELp7Ix0"> 出现相同的错误，使用测试版编码报错


一个全新的，未知的bug了属于是😵
如果可以的话请帮忙回复几个问题吧，因为你这个问题有点罕见
请问当发生错误时出现选择文件对话框了没，是选择文件后发生的错误吗
你的QQ路径是中文路径吗
你安装QQ后是否直接移动了QQ的文件夹还是在QQ安装中选择了安装在其他目录

当然，如果你只是想使用 LiteLoaderQQNT 的话，可以尝试使用[dll 过签方案](https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/tree/DLLHijackMethod)，然后再次尝试安装器或参考官方教程

**Comment by yuhao7370** [comment]
> > > 如果可以请尝试以下测试版本[操作](https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/8182009273/artifacts/1304425253)但由于您所述的`官方教程安装也是QQ其他是文件损坏`，所以不确定是否仍然存在其他问题，如果还存在问题，请提供更详细的截图
> > 
> > 
> > <img alt="错误1" width="740" src="https://private-user-images.githubusercontent.com/53969724/311943369-807b8c49-280e-4e93-b40a-af90c017e0aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDA4MTMsIm5iZiI6MTcxMDMwMDUxMywicGF0aCI6Ii81Mzk2OTcyNC8zMTE5NDMzNjktODA3YjhjNDktMjgwZS00ZTkzLWI0MGEtYWY5MGMwMTdlMGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAzMjgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYzdiZTI3ZDc2YzE0OTU1ZGUzMTAyZTVkMTk0ZjVmZGE4Y2EzMjAwNzc5N2E5MTllNjY5MmVhZDFhODNlMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._uAuQFgGI0X_ST89XRVJpArXtT_jwquoIKVtELp7Ix0"> 出现相同的错误，使用测试版编码报错
> 
> 一个全新的，未知的bug了属于是😵 如果可以的话请帮忙回复几个问题吧，因为你这个问题有点罕见 请问当发生错误时出现选择文件对话框了没，是选择文件后发生的错误吗 你的QQ路径是中文路径吗 你安装QQ后是否直接移动了QQ的文件夹还是在QQ安装中选择了安装在其他目录
> 
> 当然，如果你只是想使用 LiteLoaderQQNT 的话，可以尝试使用[dll 过签方案](https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/tree/DLLHijackMethod)，然后再次尝试安装器或参考官方教程

 这个bug纯属是我的失误。我选择文件的时候没注意选到了原版的QQ而不是NTQQ才导致的bug

要防止我这种弱智再出现可以采取以下办法：


`qq_exe_path = "C:\Program Files\Tencent\QQNT\QQ.exe"
        if not os.path.exists(qq_exe_path):
            qq_exe_path = get_qq_exe_path()`

**Comment by Mzdyl** [comment]
> > > > 如果可以请尝试以下测试版本[操作](https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/8182009273/artifacts/1304425253)但由于您所述的`官方教程安装也是QQ其他是文件损坏`，所以不确定是否仍然存在其他问题，如果还存在问题，请提供更详细的截图
> > > 
> > > 
> > > <img alt="错误1" width="740" src="https://private-user-images.githubusercontent.com/53969724/311943369-807b8c49-280e-4e93-b40a-af90c017e0aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDA4MTMsIm5iZiI6MTcxMDMwMDUxMywicGF0aCI6Ii81Mzk2OTcyNC8zMTE5NDMzNjktODA3YjhjNDktMjgwZS00ZTkzLWI0MGEtYWY5MGMwMTdlMGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAzMjgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYzdiZTI3ZDc2YzE0OTU1ZGUzMTAyZTVkMTk0ZjVmZGE4Y2EzMjAwNzc5N2E5MTllNjY5MmVhZDFhODNlMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._uAuQFgGI0X_ST89XRVJpArXtT_jwquoIKVtELp7Ix0"> 出现相同的错误，使用测试版编码报错
> > 
> > 
> > 一个全新的，未知的bug了属于是😵 如果可以的话请帮忙回复几个问题吧，因为你这个问题有点罕见 请问当发生错误时出现选择文件对话框了没，是选择文件后发生的错误吗 你的QQ路径是中文路径吗 你安装QQ后是否直接移动了QQ的文件夹还是在QQ安装中选择了安装在其他目录
> > 当然，如果你只是想使用 LiteLoaderQQNT 的话，可以尝试使用[dll 过签方案](https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/tree/DLLHijackMethod)，然后再次尝试安装器或参考官方教程
> 
> 这个bug纯属是我的失误。我选择文件的时候没注意选到了原版的QQ而不是NTQQ才导致的bug
> 
> 要防止我这种弱智再出现可以采取以下办法：
> 
> `qq_exe_path = "C:\Program Files\Tencent\QQNT\QQ.exe" if not os.path.exists(qq_exe_path): qq_exe_path = get_qq_exe_path()`

😂问题不大，我说为什么出现了奇奇怪怪报错
然后你所说的那个路径判断已经在代码中有了，是通过优先注册表读取QQNT路径，注册表路径不存在再触发手动选择（之所以不直接写 "C:\Program Files\Tencent\QQNT\QQ.exe" 是因为有用户喜欢安装在其他目录，用注册表获取更方便
总而言之，感谢反馈以及祝你使用愉快
