### ISSUE TITLE
Linux-Ubuntu2204 fatal:不能创建工作区目录'pluginStore':权限不够

### ISSUE THREAD

**Issue by buynonsense** [Mzdyl/LiteLoaderQQNT_Install#29]

**Comment by Mzdyl** [comment]
如果可以的话麻烦提供运行截图，目前并无法复现您所述的问题，导致无法确定问题所在

**Comment by buynonsense** [comment]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/97596221/f33477a6-44f1-4422-9f87-59e77e90f31a)

**Comment by buynonsense** [comment]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/97596221/39175514-2d50-46e7-9ec3-07881051d3e4)

**Comment by buynonsense** [comment]
> ![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/97596221/39175514-2d50-46e7-9ec3-07881051d3e4)
> 

怪事，我进/.config 吧Lite插件目录rm后，再运行脚本就通过了

**Comment by buynonsense** [comment]
但是上qq一看 依然是只有LiteLoaderQQNT，但里面没有插件市场
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/97596221/74fbf8dc-b715-40a6-8f90-65e833e9388d)
