### ISSUE TITLE
未检测QQNT\resources\app\LiteLoaderQQNT_bak导致再次安装时无法正常安装

### ISSUE THREAD

**Issue by bling-yshs** [Mzdyl/LiteLoaderQQNT_Install#32]
QQNT更新以后要重新用exe脚本安装，但是安装时提示如下图：
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/41812674/a3ad74c7-684e-4f60-bb0b-1db08741a7fc)
删除C:/Program Files/Tencent/QQNT/resources/app/LiteLoaderQQNT_bak后可以正常安装

**Comment by Mzdyl** [comment]
这个问题是由于QQ正在运行中，无法对相关目录进行操作导致的，现在已在脚本中修复(通过运行脚本时检测QQ进程，关闭相关进程)
至于 https://github.com/Mzdyl/LiteLoaderQQNT_Install/issues/31 ，由于使用了较为简单的比较版本方式导致了错误，也已修复
请稍后尝试更新后的版本，如还有错误，欢迎反馈

**Comment by bling-yshs** [comment]
> 这个问题是由于QQ正在运行中，无法对相关目录进行操作导致的，现在已在脚本中修复(通过运行脚本时检测QQ进程，关闭相关进程) 至于[action构建出来的exe，启动后会提示有更新，所以没法用](https://github.com/Mzdyl/LiteLoaderQQNT_Install/issues/31) ，由于使用了较为简单的比较版本方式导致了错误，也已修复 请稍后尝试更新后的版本，如还有错误，欢迎反馈

我下载了最新的 https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/8582302512 ，还是一样的问题
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/41812674/082d6723-60cc-4eac-8f0c-4914f0a0bef9)

**Comment by Mzdyl** [comment]
啊这，重新看了一下，
代码中是使用了
`shutil.rmtree(os.path.join(file_path, 'resources', 'app', 'LiteLoaderQQNT_bak'), ignore_errors=True)`
移除旧版备份
一般未能成功可能性基本就是其他进程正在使用该目录或文件或者权限问题
不过既然都不是的话，那可能是其他原因，可能需要你将 ignore_errors=True 注释掉，检查错误输出
或者电脑运行 
```import os
import winreg
import shutil


registry_hive = winreg.HKEY_LOCAL_MACHINE
registry_subkey = r"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\QQ"
registry_value_name = "UninstallString"
uninstall_string = read_registry_key(registry_hive, registry_subkey, registry_value_name)
qq_exe_path = uninstall_string.replace("Uninstall.exe", "QQ.exe")
file_path = os.path.dirname(qq_exe_path)

shutil.rmtree(os.path.join(file_path, 'resources', 'app', 'LiteLoaderQQNT_bak'))
```
看一下报错信息

**Comment by bling-yshs** [comment]
> 啊这，重新看了一下， 代码中是使用了 `shutil.rmtree(os.path.join(file_path, 'resources', 'app', 'LiteLoaderQQNT_bak'), ignore_errors=True)` 移除旧版备份 一般未能成功可能性基本就是其他进程正在使用该目录或文件或者权限问题 不过既然都不是的话，那可能是其他原因，可能需要你将 ignore_errors=True 注释掉，检查错误输出 或者电脑运行
> 
> ```
> import winreg
> import shutil
> 
> 
> registry_hive = winreg.HKEY_LOCAL_MACHINE
> registry_subkey = r"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\QQ"
> registry_value_name = "UninstallString"
> uninstall_string = read_registry_key(registry_hive, registry_subkey, registry_value_name)
> qq_exe_path = uninstall_string.replace("Uninstall.exe", "QQ.exe")
> file_path = os.path.dirname(qq_exe_path)
> 
> shutil.rmtree(os.path.join(file_path, 'resources', 'app', 'LiteLoaderQQNT_bak'))
> ```
> 
> 看一下报错信息

```
PermissionError: [WinError 5] 拒绝访问。: 'C:/Users/yshs/Desktop/LiteLoaderQQNT_bak\\plugins\\mspring_theme\\.git\\objects\\04\\9b00d14136644ba86c52a67e0edbbad7566159'
```
我给把这个文件夹移动到桌面了删不掉，看起来是这个库有点小问题，等下我删掉里面的git文件试试

**Comment by bling-yshs** [comment]
还真是这个git文件夹的问题，emm

**Comment by bling-yshs** [comment]
让AI写了份，试了下确实可以了，我吃个饭看看能不能交个PR吧
```python
import os
import shutil
import stat
def remove_dir(dir_path):
    # 遍历目录
    for root, dirs, files in os.walk(dir_path, topdown=False):
        # 更改文件权限
        for name in files:
            path = os.path.join(root, name)
            os.chmod(path, stat.S_IWRITE)
        # 更改目录权限
        for name in dirs:
            path = os.path.join(root, name)
            os.chmod(path, stat.S_IWRITE)
    # 尝试删除目录
    shutil.rmtree(dir_path)

# 调用函数删除目录
remove_dir('C:/Users/yshs/Desktop/LiteLoaderQQNT_bak')

```

**Comment by bling-yshs** [comment]
https://github.com/Mzdyl/LiteLoaderQQNT_Install/pull/33
