### ISSUE TITLE
安装过程中出现错误

### ISSUE THREAD

**Issue by goblock2021** [Mzdyl/LiteLoaderQQNT_Install#35]
发生错误: [Errno 2] No such file or directory: 'C:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT_bak\\config.json'

**Comment by goblock2021** [comment]
我把所有插件文件删除重装了，然后QQ报错
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/114788565/2ed8318d-f829-4741-b323-96a873833ae9)

**Comment by Mzdyl** [comment]
发生错误: [Errno 2] No such file or directory: 'C:\Program Files\Tencent\QQNT\resources\app\LiteLoaderQQNT_bak\config.json'


这个错误没有影响，新版 LiteLoaderQQNT 更改了 config.json，不影响使用


第二个错误emmm，感觉像是多删东西了

**Comment by dongbao66** [comment]
更新了老哥
