### ISSUE TITLE
安装过程中出错

### ISSUE THREAD

**Issue by XxhutaoxX** [Mzdyl/LiteLoaderQQNT_Install#36]
安装过程中提示拒绝访问
![出错截图](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/121332754/e3c29e0d-edc9-480f-b3bf-7f273a5a449a)
我使用了管理员权限启动

**Comment by Mzdyl** [comment]
参考#32
移除plugins 内 mspring_theme 插件中的 .git 文件
（或者直接移动LiteloaderQQNT-main 到其他地方，然后重装liteloader，装好后再重新移动plugins 和 data 会目录恢复数据

**Comment by XxhutaoxX** [comment]
好的谢谢
