### ISSUE TITLE
好像并没有安装插件商店啊

### ISSUE THREAD

**Issue by 1592363624** [Mzdyl/LiteLoaderQQNT_Install#4]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/50036597/cc508f79-5995-4143-b8df-66bc859d6bba)

**Comment by Clackz** [comment]
应用商店插件的文件没有新建文件夹，而是直接丢在了plugins目录下，导致插件没有被识别

**Comment by 1592363624** [comment]
> 应用商店插件的文件没有新建文件夹，而是直接丢在了plugins目录下，导致插件没有被识别

应该是的  然后我自己下载的应用商店  一个文件夹丢在插件目录下面就可以了

**Comment by Mzdyl** [comment]
感谢反馈，因为测试过程会启动QQ，此时会自动创建 plugins 文件夹，因为未检测出此问题
现已修复，如仍有其他问题欢迎反馈
