### ISSUE TITLE
arch linux的aur有liteloaderqqnt-bin，安装此软件包可以完成llqqnt安装的所有步骤，建议添加提示

### ISSUE THREAD

**Issue by serverbread** [Mzdyl/LiteLoaderQQNT_Install#46]
建议检测发行版，如果是arch的话就提示用户，询问是否使用aur助手安装，或从aur下载并makepkg -si，又或者仍用此脚本安装

**Comment by Mzdyl** [comment]
感觉必要性不大，不过日后可以添加

**Comment by Mzdyl** [comment]
功能初步实现了https://github.com/Mzdyl/LiteLoaderQQNT_Install/commit/fcec9a53c9d94ea9b2b27ff0e013fac1530df6d2 ，将在后续更新和发布
