### ISSUE TITLE
Linux安装命令问题

### ISSUE THREAD

**Issue by model-err** [Mzdyl/LiteLoaderQQNT_Install#47]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/62633762/1c9c77e4-a1ef-47d9-9324-cbed9c0050c4)
问题图像如上。当使用zsh运行时，会直接崩溃，似乎是使用了bash而非zsh语法但是由zsh执行导致的。
建议直接改为：
`curl -L "https://github.com/Mzdyl/LiteLoaderQQNT_Install/releases/latest/download/install_linux.sh" | bash`

**Comment by Jackhr-arch** [comment]
https://github.com/Mzdyl/LiteLoaderQQNT_Install/blob/main/install_linux.sh#L1-L1

不过怎么会在zsh上崩溃呢，奇怪🤔

**Comment by Jackhr-arch** [comment]
是 `[ "$VAR" == "VALUE" ]` 的问题，zsh只允许一个`=`，这个[commit](https://github.com/Mzdyl/LiteLoaderQQNT_Install/commit/e7a119a8d92141a6bdfe564e8bca3268e4b14db9#diff-1bc27d9f28c3c64e5570647a221987b0cd49ccdfc010bc8c5ca7f68f64b73a26R28) 应当已经修复了这个问题

**Comment by model-err** [comment]
是，我觉得我该关掉了，但是扔到/tmp但是安装完不删不是个好习惯
