### ISSUE TITLE
安装后无法启动QQ

### ISSUE THREAD

**Issue by 114cloud** [Mzdyl/LiteLoaderQQNT_Install#5]
运行exe后出现如下报错
我是0.x 版本的老用户想升级到 1.x 版本，QQ的版本是9.9.2.16183，我是否应该提供更多信息？以及请问一下该如何解决
![屏幕截图 2024-01-25 163356](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/148178844/bc10b049-3b53-48a5-8229-7749a454dfdf)

**Comment by 114cloud** [comment]
卸载重新安装QQ后再运行脚本就正常了（

**Comment by Mzdyl** [comment]
如果只是想使用 LiteLoaderQQNT 推荐卸载重装 QQ 再运行 exe 最快

如果不想的话请尝试检查一下 D:/QQNT/resources/app/package.json 文件是否仍有 0.x 修改痕迹

**（因为旧版有太多种安装框架的方法，我没办法一一适配，所以有bug不好寻找与修复，重装是最快最方便的方法**
