### ISSUE TITLE
安装完成了没有效果

### ISSUE THREAD

**Issue by 1592363624** [Mzdyl/LiteLoaderQQNT_Install#50]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/50036597/1441c087-05d9-4513-b188-6d81c5f33e03)

**Comment by Mzdyl** [comment]
<img width="1030" alt="截屏2024-05-11 15 04 24" src="https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/25149539/e73e3fa9-d9e2-4892-a4ec-7a2be95300be">
<img width="825" alt="截屏2024-05-11 15 04 33" 
src="https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/25149539/4015dbe6-e43a-4f33-a48d-064bcd522fc3">


如若可以检查一下QQ 目录下的QQNT\resources\app
和 QQNT\resources\app\app_launcher\index.js内是否有修改

因为看截图没有什么执行失败的报错，也可以试试管理员权限运行

**Comment by 1592363624** [comment]
> <img alt="截屏2024-05-11 15 04 24" width="1030" src="https://private-user-images.githubusercontent.com/25149539/329761737-e73e3fa9-d9e2-4892-a4ec-7a2be95300be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTY2MDcsIm5iZiI6MTcxNTQxNjMwNywicGF0aCI6Ii8yNTE0OTUzOS8zMjk3NjE3MzctZTczZTNmYTktZDllMi00ODkyLWE0ZWMtN2EyYmU5NTMwMGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA4MzE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ODcyYWRiYzEwNDAwNzhkYmE0Y2IzYzcwNmIzZTk5MjY2MjMzYWZlOGVmNjcwZTI2NjZiM2YxM2JkOTI1MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5pA7JNbdK3DmKttZ0KFmGThqPan2YS1Ry-7uZF8w7QQ"> <img alt="截屏2024-05-11 15 04 33" width="825" src="https://private-user-images.githubusercontent.com/25149539/329761739-4015dbe6-e43a-4f33-a48d-064bcd522fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTY2MDcsIm5iZiI6MTcxNTQxNjMwNywicGF0aCI6Ii8yNTE0OTUzOS8zMjk3NjE3MzktNDAxNWRiZTYtZTQzYS00ZjMzLWE0OGQtMDY0YmNkNTIyZmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA4MzE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZTI1NmE0NDc3MDM5YmRjNjA0MTM5NzZkYTU5OGVlYTg2YzBjZjRmNmJhYjMxZWM4OGE2N2JlZDFiMWUyMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.huElc7gurjyKQrqJ27cIC_r85qHTjwkUrwTqgE7nk0I">
> 如若可以检查一下QQ 目录下的QQNT\resources\app 和 QQNT\resources\app\app_launcher\index.js内是否有修改
> 
> 因为看截图没有什么执行失败的报错，也可以试试管理员权限运行

![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/50036597/68ca5101-6e6c-45e6-af0f-ec161421ba4c)
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/50036597/8b46a13a-648f-45bb-a977-75aff6659ade)

目测是和你那差不多的  应该没问题吧

**Comment by 1592363624** [comment]
之前本来一直也是用的你这个安装器安装的,但是前两天在商店更新了一个插件后重启QQ就啥都没了

**Comment by Mzdyl** [comment]
嗷，可能插件问题，之前群里有过类似的案例，有的插件可能会导致 LL 无法正常启动
可以吧插件全部移除在尝试

**Comment by 1592363624** [comment]
> 嗷，可能插件问题，之前群里有过类似的案例，有的插件可能会导致 LL 无法正常启动 可以吧插件全部移除在尝试

确实  插件全部删除就好了
