### ISSUE TITLE
安装过程中提示错误

### ISSUE THREAD

**Issue by mingyoucao** [Mzdyl/LiteLoaderQQNT_Install#51]
![install_windows_auYcAN8E4e](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/96685208/f44a1c43-c2e9-4626-a5b4-77bbe2b5661c)

**Comment by Mzdyl** [comment]
请先参考这个吧 https://github.com/Mzdyl/LiteLoaderQQNT_Install/issues/36 解决吧
因为这个问题我没能复现，试了几种解决方法都好像效果不佳，有空我在换种方法尝试修复
