### ISSUE TITLE
pre1.13不会将数据文件夹放入实际的用户目录，而是默认的C盘内

### ISSUE THREAD

**Issue by abbaccadd0** [Mzdyl/LiteLoaderQQNT_Install#52]
字面意思，我的Documents被移动到了D盘，比如
`D:\Users\user_name\Documents`
但1.13的安装器会将数据文件夹直接塞入
`C:\Users\user_name\Documents`
这应该是不符合预期的，因此作为Bug提交

**Comment by LY-Xiang** [comment]
关于这个问题
我的想法是通过环境变量%USERPROFILE%解决

**Comment by LY-Xiang** [comment]
> 关于这个问题
> 我的想法是通过环境变量%USERPROFILE%解决

检查了一下
发现已经以此方法获取目录
请检查一下您的环境变量是否正常

**Comment by abbaccadd0** [comment]
> 关于这个问题 我的想法是通过环境变量%USERPROFILE%解决

这个问题无法使用%USERPROFILE%来解决
因为这个环境变量仅仅指向当前用户文件夹所在的位置，但是如果Documents不在这个文件夹内的话，就没有意义。

建议使用
```
from win32com.shell import shell
print(shell.SHGetFolderPath(0, 5, None, 0))
```
来获取Documents文件夹的位置

抱歉截图水平有限，但是如图
![test](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/39579855/6f90ecd1-0551-42a5-aeeb-f6c714a85dd5)
第二个才是实际上Documents的路径。

**Comment by LY-Xiang** [comment]
收到
我会尝试后提pr

**Comment by Mzdyl** [comment]
感谢提醒，最开始确实没想到这种情况
以及期待及感谢 @LY-Xiang 将要和已经提交的pr🥰
