### ISSUE TITLE
BUG: 安装后找不到模块

### ISSUE THREAD

**Issue by jinyu2022** [Mzdyl/LiteLoaderQQNT_Install#56]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/96060102/88479e31-f0f3-4e5e-800f-460934d49b0d)
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/96060102/607f15dd-77be-4278-9ee0-adf9f22e9270)

**Comment by jinyu2022** [comment]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/96060102/b6b16c26-90f3-4334-ae15-a0c40a14b17a)

**Comment by jinyu2022** [comment]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/96060102/77d17934-c90e-405a-a08a-91ff035b0a69)

**Comment by Mzdyl** [comment]
额，请问电脑上有无安装git

**Comment by Mzdyl** [comment]
代码显示运行 git 未找到
（讲真我以为Linux 和 mac 用户大部分都会安装git
所以写代码时直接用 git 拉取的 LiteLoaderQQNT
然后大部分也确实都有 git，导致我都没意识到还有这个潜在可能😵

后续将会在之后版本中替换 git 下载方式，现在还请先使用 包管理器 安装 git 后再次运行脚本吧
至于最后一张图那个问题因为文档更新改了路径，现在已经修复了

**Comment by jinyu2022** [comment]
我也好奇一个月前第一次可以用，现在不行了。搞得我死去活来。其实是有git的我今天重新安装环境掉了
最掉发的问题永远是最无语的问题
