### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。>

### ISSUE THREAD

**Issue by 1592363624** [Mzdyl/LiteLoaderQQNT_Install#6]
![Shell截图_20240126202832](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/50036597/2eb2fc0d-cf08-4df8-8ea3-b23e6729528d)

回家用台式装就这样子了

正常网络和VPN都试过了

**Comment by Mzdyl** [comment]
啊这，这个这个属实没办法，可能是最近网络封的严，亦或者什么奇奇怪怪的原因
可以先自行尝试下 Google 上的解决方案

**有空我把LiteLoaderQQNT一并打包，实现默认网络拉取，拉取失败使用封装好的本地文件**
~~（不过最近太忙，不定啥时候实现，挖坑ing~~
