### ISSUE TITLE
关于github勋章显示LL与最新版qq兼容状态的疑问

### ISSUE THREAD

**Issue by jiongjiongJOJO** [Mzdyl/LiteLoaderQQNT_Install#61]
看到todo list新增了一项：
> - [ ] [README.md](https://github.com/Mzdyl/LiteLoaderQQNT_Install/blob/main/README.md) 使用GitHub徽章显示通过自动化 ci 监测 LL 与 QQ 最新版的兼容状态

这个todo的意思是不是如果QQ更新了或者LL更新了，需要触发github Action，从而实现版本的兼容性监控。

如果是这样的话，需要考虑有个程序定时监控QQ和LL的更新，可以选择新建一个仓库，使用Github Action定时触发器完成，也可以服务器部署脚本，检测到更新后，利用Github API，主动触发Action。

**Comment by Mzdyl** [comment]
其实只是打算单纯弄个每周自动运行ci
然后输出 当前测试版本 测试结果 ，通过徽章展示在 README 里
而已，毕竟其他的整太多就太复杂了，这不过只是个安装器而已😂

**Comment by jiongjiongJOJO** [comment]
> 其实只是打算单纯弄个每周自动运行ci 然后输出 当前测试版本 测试结果 ，通过徽章展示在 README 里 而已，毕竟其他的整太多就太复杂了，这不过只是个安装器而已😂

那这样的话，只需要定期执行现有的workflow就行，在每个workflow里添加如下内容即可。
```yaml
on:
  schedule:
    - cron: '0 0 */7 * *'
```

**Comment by Mzdyl** [comment]
主要没想好怎么实现 展示当前版本号 到 徽章
这个 徽章 功能没太看懂
想到的实现比较复杂，感觉不太对

**Comment by jiongjiongJOJO** [comment]
> 主要没想好怎么实现 展示当前版本号 到 徽章 这个 徽章 功能没太看懂 想到的实现比较复杂，感觉不太对

如果想要动态的展示版本号，可能就需要action定时提交更新后的README.md文件。或者说，利用外部网站展示一个html标签

**Comment by Mzdyl** [comment]
嗷对，应该可以开个分支存放版本号相关信息
读取 特定分支内 内容实现动态展示
毕竟感觉在主分支内更新 README.md 有点乱
（虽然已经够乱的了😮‍💨
等有空着试试，感觉这样应该不难实现

**Comment by jiongjiongJOJO** [comment]
另外还有一点，我觉得可以考虑一下多平台的兼容性问题，使用同一套代码，完成不同平台的构建，这样在CI处理的时候，也可以将多平台的处理合并到一起，类似于opencv-python仓库那样。
https://github.com/opencv/opencv-python/actions
![Clip_2024-05-22_16-30-46](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/58727904/fcfca7ef-f40e-424f-9cfc-7acad55a955e)

**Comment by Mzdyl** [comment]
> 另外还有一点，我觉得可以考虑一下多平台的兼容性问题，使用同一套代码，完成不同平台的构建，这样在CI处理的时候，也可以将多平台的处理合并到一起，类似于opencv-python仓库那样。 https://github.com/opencv/opencv-python/actions ![Clip_2024-05-22_16-30-46](https://private-user-images.githubusercontent.com/58727904/332721751-fcfca7ef-f40e-424f-9cfc-7acad55a955e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjcwNjAsIm5iZiI6MTcxNjM2Njc2MCwicGF0aCI6Ii81ODcyNzkwNC8zMzI3MjE3NTEtZmNmY2E3ZWYtZjQwZS00MjRmLTljZmMtN2FjYWQ1NWE5NTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA4MzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NTUzYjYzYjlmYjJiYjg1ZDE3ZjhjYzhiYjE5NzdlN2M3NjlmM2NlYjg4YmNmYWRjOTJjZDRkYjIwZGZlY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a8C3qAUzwdxj2jchOivM_aDrlKZND9F16sCJkDXWWuM)
> 
> 或者也可以在workflow的yaml文件里动手脚

目前来说好像没什么多平台需求
也就 windows 需要构建exe
其他平台仅仅是监测测试结果而已
写`监测 LL 与 QQ 最新版的兼容状态 `倒是可以尝试一下，但感觉会使监测变得复杂，等到时看看再说吧
