### ISSUE TITLE
发生错误: 'utf-8' codec can't decode byte 0xce in position 3: invalid continuation byte

### ISSUE THREAD

**Issue by Qian-F** [Mzdyl/LiteLoaderQQNT_Install#62]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/111696321/49336f87-ec0e-4092-a6f4-b87ed8211a5b)
版本：9.9.10-23873(64位)
使用最新脚本

**Comment by Qian-F** [comment]
使用 [1.12](https://github.com/Mzdyl/LiteLoaderQQNT_Install/releases/tag/1.12) 版本无任何问题

**Comment by jiongjiongJOJO** [comment]
#55 对获取Documents目录的方法做了调整，导致了这个问题。顺便提一下，能否提供你电脑完整的Documents目录，用于分析数据？
例如：`C:\Users\JOJO\Documents`

**Comment by jiongjiongJOJO** [comment]
> #55 对获取Documents目录的方法做了调整，导致了这个问题。顺便提一下，能否提供你电脑完整的Documents目录，用于分析这个异常？ 例如：`C:\Users\JOJO\Documents`

如果目录中含有个人隐私，可以替换成其他的字符，并且注明是否为标准中文字符，还是其他特殊的标点符号

**Comment by jiongjiongJOJO** [comment]
https://github.com/jiongjiongJOJO/LiteLoaderQQNT_Install/actions/runs/9206776407

可以尝试一下我刚提交的这个版本，由于代码并未合并到本仓库，需要你运行时有分辩异常的能力（当然我本人保证没有做不合法操作🤣）

**Comment by jiongjiongJOJO** [comment]
> [jiongjiongJOJO/LiteLoaderQQNT_Install/actions/runs/9206776407](https://github.com/jiongjiongJOJO/LiteLoaderQQNT_Install/actions/runs/9206776407)
> 
> 可以尝试一下我刚提交的这个版本，由于代码并未合并到本仓库，需要你运行时有分辩异常的能力（当然我本人保证没有做不合法操作🤣）

当然 #52 最好也测试一下这个是否能正常获取。

**Comment by Qian-F** [comment]
好 我稍后会尝试

**Comment by Qian-F** [comment]
有一个小问题
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/111696321/18b3d06b-721a-4acd-9321-c2cbdb793292)
不过其他操作都成功了
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/111696321/ad19f567-6be1-457c-9890-2e7aee8b9511)

**Comment by jiongjiongJOJO** [comment]
> 有一个小问题 ![image](https://private-user-images.githubusercontent.com/111696321/333580447-18b3d06b-721a-4acd-9321-c2cbdb793292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTMxMDAsIm5iZiI6MTcxNjU1MjgwMCwicGF0aCI6Ii8xMTE2OTYzMjEvMzMzNTgwNDQ3LTE4YjNkMDZiLTcyMWEtNGFjZC05MzIxLWMyY2JkYjc5MzI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxMjEzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDU0NDZkOTI3ZDY2NzBhODc3NzE3MWI3NGMyOWIwNDFjNzJjYWY0NzY0ODc3MGVkMjJkZGNhYTQ0NjcxZTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zU7EP9pYngrpEqU8t62Em0yHJCuUuWD3-yCevpZMMRo) 不过其他操作都成功了 ![image](https://private-user-images.githubusercontent.com/111696321/333580390-ad19f567-6be1-457c-9890-2e7aee8b9511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTMxMDAsIm5iZiI6MTcxNjU1MjgwMCwicGF0aCI6Ii8xMTE2OTYzMjEvMzMzNTgwMzkwLWFkMTlmNTY3LTZiZTEtNDU3Yy05ODkwLTJlN2FlZThiOTUxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxMjEzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDkwMGY1MTI1ZWM2ZjBhMmQ1ZTE3ZmRkMjliODJkODA2YjRiNjE0MDQxZTJjMmE5NjU3MWE0OThjZTA4OTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gDD5Kfn5uBj8J2iFG2STk5k4MSESSUBVgcCp58UYe1o)

嗯，那证明目前修改的方法是可以正常获取Documents目录的，后面可以合并到release版本。
另外你提到的这个东西，是另外的一个bug，需要作者分析一下原因，这一块我后续把堆栈信息输出，便于分析吧。

**Comment by Qian-F** [comment]
好的 那这个issue我关闭了

**Comment by LY-Xiang** [comment]
python的decode默认utf-8
但是通过windows的函数获取的格式为ansi
@jiongjiongJOJO 已经用注册表修了 感谢
