### ISSUE TITLE
建议把插件列表查看替代已删库的插件商店

### ISSUE THREAD

**Issue by OiCkilL** [Mzdyl/LiteLoaderQQNT_Install#65]
[插件列表查看](https://github.com/ltxhhz/LL-plugin-list-viewer) 已实现插件商店的大部分功能了，建议安装时可选预装该插件

**Comment by Mzdyl** [comment]
可以，将在后续版本实现

**Comment by Mzdyl** [comment]
已经实现了，目前已在测试版推出
待稳定后将正式发布
