### ISSUE TITLE
安装完毕，但打开NTQQ出现报错弹窗

### ISSUE THREAD

**Issue by StqGo** [Mzdyl/LiteLoaderQQNT_Install#7]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/96059236/bbe373d1-78b0-47e9-97c5-f87420af7f19)
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/96059236/25bb3963-0a62-45b2-a75d-2c153a29752f)
小白不太懂，是因为安装目录不能出现中文吗

**Comment by RunAway95** [comment]
我跟你一样的问题
resources\app\app_launcher\index.js
这个文件 直接用记事本打开 另存为 编码选UTF-8 覆盖之前的文件就行

**Comment by Mzdyl** [comment]
已经修复 中文路径 情况，将于下个版本推送，不过不推荐使用中文路径
中文路径可能导致其他插件产生未知错误

**Comment by StqGo** [comment]
感谢回复，已通过修改NTQQ安装路径解决
