### ISSUE TITLE
安装时因为无法拉取仓库而报错

### ISSUE THREAD

**Issue by Starcloudsea** [Mzdyl/LiteLoaderQQNT_Install#72]
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/84891987/965671bf-b85d-4ecf-9220-34e2c60af368)
报错大概是这样，看起来是镜像站无法访问的问题，话说有打算添加多个镜像站或者添加在遇到这类报错时让用户自定义网站前缀的功能吗？
~~以及，我这样的情况，有临时的修复方法吗？🤔~~好像我可以下载源代码改一下（应该能行😁）

**Comment by Mzdyl** [comment]
现在是镜像站写死在代码第23行
多镜像站或自定义镜像站应该可以实现
（主要 github 感觉没啥其他稳定的镜像站
最好的临时解决方法是临时开个梯子（bushi

**Comment by Starcloudsea** [comment]
> 现在是镜像站写死在代码第23行 多镜像站或自定义镜像站应该可以实现 （主要 github 感觉没啥其他稳定的镜像站 最好的临时解决方法是临时开个梯子（bushi

其实Moeyy挺不错的（（（

**Comment by Mzdyl** [comment]
> > 现在是镜像站写死在代码第23行 多镜像站或自定义镜像站应该可以实现 （主要 github 感觉没啥其他稳定的镜像站 最好的临时解决方法是临时开个梯子（bushi
> 
> 其实Moeyy挺不错的（（（ 我刚刚也改了源代码，改成Moeyy的镜像站没出一点问题（喜）

有空我看看，好用的话改为多镜像站

**Comment by Starcloudsea** [comment]
> > > 现在是镜像站写死在代码第23行 多镜像站或自定义镜像站应该可以实现 （主要 github 感觉没啥其他稳定的镜像站 最好的临时解决方法是临时开个梯子（bushi
> > 
> > 
> > 其实Moeyy挺不错的（（（ 我刚刚也改了源代码，改成Moeyy的镜像站没出一点问题（喜）
> 
> 有空我看看，好用的话改为多镜像站

有个油猴插件有一堆镜像站，可以抄抄那个（）

**Comment by CreeperAWA** [comment]
提完了issue后突然想到估计有人提差不多的，还真是，我不知道为什么我这里镜像站就不行，那个油猴脚本的镜像站都特稳定

**Comment by Mzdyl** [comment]
仿照  Github 增强 加了个多镜像站判断与选择
（不过目前镜像站列表直接全 copy 的，可用性还需进一步检查
