### ISSUE TITLE
希望可以自行选择镜像站或者使用github原地址下载

### ISSUE THREAD

**Issue by CreeperAWA** [Mzdyl/LiteLoaderQQNT_Install#73]
估计是我的问题，我总是提示
`发生错误: HTTPSConnectionPool(host='mirror.ghproxy.com', port=443): Max retries exceeded with url: /https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/archive/master.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))`
我分析了一下，应该是无法验证`mirror.ghproxy.com`的SSL证书，我这里是可以使用github原站下载的，也希望可以使用一些其他的镜像站，例如：
`https://gh.h233.eu.org/`
`'https://gh.ddlc.top/`
这两个镜像站只需要在后面加上github原本的下载链接即可，比如：
`https://gh.h233.eu.org/https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/archive/master.zip`
`https://gh.ddlc.top/https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/archive/master.zip`

**Comment by CreeperAWA** [comment]
好吧，我用我提供的两个镜像站试了一下，还是一样的报错，难受

**Comment by hfsz2313** [comment]
可以尝试把镜像链接规则写成正则或者format串

**Comment by Mzdyl** [comment]
多镜像站 和 自定义下载链接 都已经在最近提交中实现了
（不过自定义下载只会在下载失败情况下触发

**Comment by Night-GUA** [comment]
发生错误: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
