### ISSUE TITLE
无法按任意键退出

### ISSUE THREAD

**Issue by CreeperAWA** [Mzdyl/LiteLoaderQQNT_Install#74]
经过我闲得没事干的测试，发现只能按回车键和电源键退出，希望作者可以修改一下提示，或者改成真正的按任意键退出

**Comment by Mzdyl** [comment]
疏忽了，安装顺利的话会提示 按回车键退出
然后发生错误时提示信息忘改了，还是之前的 按任意键退出
之后会一并修改过来的
