### ISSUE TITLE
ISSUES 测试

### ISSUE THREAD

**Issue by Mzdyl** [Mzdyl/LiteLoaderQQNT_Install#75]
### 问题类型
请选择一个:
- [ ] 功能改进
- [ ] 其他
- [x] Bug 反馈
- [x] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [x] macOS
- [ ] Linux
- [ ] Windows

### 描述
突然意识到 issues 实现检测图片好像不好搞
~~并没有问题，只是想展示一下我画的小猫猫（bushi~~

### 错误截图
![penup_20230227_214912](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/25149539/ee056e18-4869-499b-b267-fe60e13fb4dd)

**Comment by LY-Xiang** [comment]
😰

**Comment by Starcloudsea** [comment]
猫猫可爱！
