### ISSUE TITLE
[ Feature Request ] 允许配置GitHub个人访问令牌来绕过GitHub API请求量限制

### ISSUE THREAD

**Issue by tiehu** [Mzdyl/LiteLoaderQQNT_Install#77]
### 问题类型
请选择一个:
- [ ] Bug 反馈
- [ √ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [ ] macOS
- [ ] Linux
- [ √ ] Windows

### 运行版本
请填写您的运行版本:
pro-release

### 描述
简要描述您的问题:
对于未经身份验证的请求，GitHub对每小时的请求数为**60**。这个数量是以IP地址为判断基准的，也就是说当用户使用人数较多的节点访问GitHub时，很可能会遇到API访问限制，并导致安装程序拉取仓库失败（此时GitHub本身可以正常访问因此程序不会去使用镜像源）。
对此，可以在遇到API限制时提示用户输入他们的GitHub访问令牌，这可以将请求上限提升到每小时**5000**个。或者，也可以在出现错误时直接换用镜像源重试。
更多细节详见：
https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

### 错误截图
请粘贴错误截图:

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by Mzdyl** [comment]
目前通过更新时自动使用 github action 获取最新 liteloaderQQNT 等文件并集成打包进 .exe 文件
以及脚本内 固定对应版本链接 以上两种方案以规避可能的 API请求量限制
因为对于普通用户来说 配置GitHub个人访问令牌 略有复杂
以及感谢提出高质量issues

怪，莫名其妙写的好严肃，问题不大（逃
