### ISSUE TITLE
默认使用的是github原网站，但是我找到了镜像

### ISSUE THREAD

**Issue by Cooooldwind** [Mzdyl/LiteLoaderQQNT_Install#8]
是hub.fgit.cf，把python文件里所有的github.com替换成这个，可以作为备用镜像。

**Comment by ApartTUSITU** [comment]
尽量做个自动切换镜像源的功能，哪个镜像源挂了换下一个可用的

**Comment by Mzdyl** [comment]
已经添加镜像下载功能，目前使用的是 https://mirror.ghproxy.com/
