### ISSUE TITLE
使用安装器安装后，启动 QQ 没有“插件列表查看”

### ISSUE THREAD

**Issue by EmptyDreams** [Mzdyl/LiteLoaderQQNT_Install#82]
### 问题类型
请选择一个:
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
请填写您的运行版本:
QQ：9.9.11-24815
安装器：1.13

### 描述
简要描述您的问题:

如题，安装后没有插件列表

![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/44894906/35e22514-7fae-4c98-8b52-16b3b1bd03e7)

### 错误截图
请粘贴错误截图:

安装过程没有任何报错

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by Mzdyl** [comment]
该功能在1.14版本才添加（
目前的那个pre release 版本
过几天改为正式版
