### ISSUE TITLE
安装插件商店发生错误: [Errno 2] No such file or directory: 'C:\Users\23286\AppData\Local\Temp\list-viewer'

### ISSUE THREAD

**Issue by 23286440** [Mzdyl/LiteLoaderQQNT_Install#83]
### 问题类型
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
+ [pre1.14](https://github.com/Mzdyl/LiteLoaderQQNT_Install/releases/tag/pre1.14)
+ install_windows.exe

### 描述
+ 安装插件商店发生错误: [Errno 2] No such file or directory: 'C:\\Users\\23286\\AppData\\Local\\Temp\\list-viewer'
+ Errno??Error

### 错误截图
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/102169227/3bc2fdfa-7825-404f-9d7f-7bff9917c813)

### 附加信息
版本	Windows 11 家庭中文版
版本号	24H2
安装日期	‎2024/‎4/‎4
操作系统版本	26120.961
体验	Windows Feature Experience Pack 1000.26100.8.0

**Comment by 23286440** [comment]
结束后没安装上
![image](https://github.com/Mzdyl/LiteLoaderQQNT_Install/assets/102169227/41f4a248-7847-460b-89e2-64d63fca343a)

**Comment by Mzdyl** [comment]
请先手动安装插件列表查看(插件商店)吧
可能是网络原因，没能成功下载亦或者解压异常
因为目前在旅行中没法及时检查修复，请先手动安装插件商店吧

**Comment by 23286440** [comment]
嗯



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月9日(星期二) 晚上10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mzdyl/LiteLoaderQQNT_Install] 安装插件商店发生错误: [Errno 2] No such file or directory: &#39;C:\Users\23286\AppData\Local\Temp\list-viewer&#39; (Issue #83)














 
请先手动安装插件列表查看(插件商店)吧
 可能是网络原因，没能成功下载亦或者解压异常
 因为目前在旅行中没法及时检查修复，请先手动安装插件商店吧

**Comment by qmzola** [comment]
在1.14版本中也出现此问题
![图片](https://github.com/user-attachments/assets/d5d3b590-e76f-4a37-a2ac-a12c502bf69e)

**Comment by Mzdyl** [comment]
请尝试
https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/10060310736/artifacts/1730682843
应该没问题了

**Comment by qmzola** [comment]
已经可以正常使用了，谢谢
