### ISSUE TITLE
安装完后，打开QQ时出现了错误

### ISSUE THREAD

**Issue by himetuki** [Mzdyl/LiteLoaderQQNT_Install#84]
### 问题类型
请选择一个:
- [x] Bug 反馈

### 运行平台
请选择您的运行平台:
- [x] Windows

### 运行版本
请填写您的运行版本:最新版Release，请看截图

### 描述
简要描述您的问题:请看截图

### 错误截图
请粘贴错误截图:
![image](https://github.com/user-attachments/assets/d425151d-620d-4c39-81d6-7541eddf3da8)

![image](https://github.com/user-attachments/assets/89834473-0f70-451d-8965-accbb9981dcc)

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by himetuki** [comment]
会不会与我的Documents文件夹位置更改过有关？

**Comment by Mzdyl** [comment]
有点怪，像是安装上了，但好像漏文件了
我检查检查下载部分代码逻辑，看看修修

**Comment by himetuki** [comment]
> 有点怪，像是安装上了，但好像漏文件了 我检查检查下载部分代码逻辑，看看修修

感谢，问题已经解决，就是每次打开QQ都需要花很久的时间加载
![e3c2255252f0f6bc6026e36ff108eb1d](https://github.com/user-attachments/assets/6b69fc0b-188f-4b2f-94cd-406b3a769a8d)
另外就是设置中没找到插件设置，还有占用感觉变大了

**Comment by himetuki** [comment]
哦！我看到主页说的了，
![image](https://github.com/user-attachments/assets/630aabc2-6597-4d9b-a12b-e4d60f7e51d5)
我每次更新都是用自动安装来更新LiteloaderQQNT的😢
刚使用最新的Release，我之前问题解决了，现在问题就是设置中没有 LiteLoaderQQNT，希望佬能尽早解决😭

**Comment by Mzdyl** [comment]
啊这，这个问题是插件冲突或者插件bug导致的
可以尝试重装插件
插件目录就是安装时显示的数据目录
<img width="542" alt="截屏2024-07-24 01 40 36" src="https://github.com/user-attachments/assets/d7e3f75f-30b6-416b-918c-c04291589891">

**Comment by himetuki** [comment]
> 啊这，这个问题是插件冲突或者插件bug导致的 可以尝试重装插件 插件目录就是安装时显示的数据目录 <img alt="截屏2024-07-24 01 40 36" width="542" src="https://private-user-images.githubusercontent.com/25149539/351433659-d7e3f75f-30b6-416b-918c-c04291589891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTYzNzgsIm5iZiI6MTcyMTc5NjA3OCwicGF0aCI6Ii8yNTE0OTUzOS8zNTE0MzM2NTktZDdlM2Y3NWYtMzBiNi00MTZiLTkxOGMtYzA0MjkxNTg5ODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA0NDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMGFmMTEzMzJmN2E4NDMxZWM4OGE3MWJjN2ZiN2ZkNGY3Yjg4ZTdmZTNkZTI5NjM2MjM0YWZjMGY4ODExZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T-3QjvsZ1GluPBJ0r2UGHOeh6-GWwJRfjh0Stf7ssgY">

我这就试试
