### ISSUE TITLE
使用自定义路径时变量错误，导致QQ无法启动

### ISSUE THREAD

**Issue by BnqDzj** [Mzdyl/LiteLoaderQQNT_Install#86]
### 问题类型
请选择一个:
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
1.14:latest

### 描述
在使用自定义路径，修改系统变量时的斜杠使用了"/"，导致LiteLoader API和路径相关的API失效，造成插件报错，无法启动QQ
修改变量中的"/"为"\\\"可以正常启动QQ

### 错误截图
![1721736063915](https://github.com/user-attachments/assets/e9b968a5-0977-4993-b468-4783ce5ba7df)
![1721735560525](https://github.com/user-attachments/assets/8c2cc3d7-c780-4fc5-aade-2993483b76b9)
![1721735579307](https://github.com/user-attachments/assets/e9d9bc54-5783-4424-9846-54b19155a5c5)

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by Mzdyl** [comment]
稍后修复

**Comment by Mzdyl** [comment]
请尝试
https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/10060310736/artifacts/1730682843
应该没问题了
