### ISSUE TITLE
安装完后，QQ的默认表情全部消失，贴在消息上的表情也看不见

### ISSUE THREAD

**Issue by KiroReg** [Mzdyl/LiteLoaderQQNT_Install#88]
### 问题类型
请选择一个:
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
请填写您的运行版本:
NTQQ 9.9.12-25765 脚本 最新版release
### 描述
简要描述您的问题:
覆盖安装ntqq后，启动ntqq有默认表情存在。关闭ntqq并以管理员权限安装一键脚本后，启动ntqq有“liteloderqqnt”和”插件列表查看“存在。其他功能都正常，但是qq默认表情消失，具体请参照图片，另附脚本安装信息。
### 错误截图
请粘贴错误截图:
![PixPin_2024-07-23_23-31-43](https://github.com/user-attachments/assets/ef85d2d3-02aa-4833-a947-fcf759747490)
![PixPin_2024-07-23_23-37-40](https://github.com/user-attachments/assets/3d879e56-8e2c-47d9-bde3-437fdc85f914)
![PixPin_2024-07-23_23-39-56](https://github.com/user-attachments/assets/a055da52-758c-41ae-a719-3af7805925e9)
![PixPin_2024-07-23_23-43-12](https://github.com/user-attachments/assets/36be49f6-78d6-48d9-bf52-e841cbc71396)
![PixPin_2024-07-23_23-40-39](https://github.com/user-attachments/assets/081a8b76-ef5d-4381-830c-c4147b66be85)
若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by Mzdyl** [comment]
https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/333

可参考，或者等 LiteLoaderQQNT 修复
本项目只负责安装，框架问题不做处理

不过应该问题不大？反馈这个此bug的人好像也不少，估计过一阵就修复了（

**Comment by KiroReg** [comment]
ok，白天在上班没看到回复，谢谢。

**Comment by long45343** [comment]
修好了
等推送
欧耶(

**Comment by Mzdyl** [comment]
LiteloaderQQNT 已修复并推送
问题先关闭了，若仍有问题请重新打开
