### ISSUE TITLE
Windows系统语言en-US下输出为乱码

### ISSUE THREAD

**Issue by Minecrafter-Pythoner** [Mzdyl/LiteLoaderQQNT_Install#90]
### 问题类型
请选择一个:
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
请填写您的运行版本: Latest Release (1.14) nuitka

### 描述
简要描述您的问题: Windows系统语言为en-US时，运行输出全部为乱码

### 错误截图
请粘贴错误截图:
![image](https://github.com/user-attachments/assets/e0c2fb73-2e45-460c-a943-8807523ae570)

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by Minecrafter-Pythoner** [comment]
补充：
winver：
![image](https://github.com/user-attachments/assets/2f0c66b9-9c56-4158-966f-a9a1313d7e4d)
该系统以en-US安装，未将系统语言设置为其它语言过，出现此现象；
另一台Windows 11笔记本（出厂为家庭中文版，后升级为专业版且系统语言切换为en-US）无此现象，窗口能够正常输出中文字符。

**Comment by Mzdyl** [comment]
感觉像是字体缺失的问题
可以试试 设置-系统-可选功能 添加简体中文补充字体 或者 设置-时间与语言 添加中文包
<img width="1046" alt="截屏2024-07-27 11 44 27" src="https://github.com/user-attachments/assets/1d4f3a0a-4d16-4d02-b895-6a129108e5c0">

因为该情况比较少见，可能会后续重装系统时顺便测测修复？或者干脆检测到en-US 使用英文输出

**Comment by Minecrafter-Pythoner** [comment]
![image](https://github.com/user-attachments/assets/084e2324-e996-46e0-9400-72d6d56e8c8e)
![image](https://github.com/user-attachments/assets/73ba260b-4b92-494b-87a4-ff4525059af6)
<img width="343" alt="image" src="https://github.com/user-attachments/assets/1382306f-618c-4b1b-8b20-2e80eb6225a6">
如图，经检查中文补充字体与简体中文本地体验包在使用程序前就已经安装并能够正确使用

**Comment by LY-Xiang** [comment]
有可能是不同默认语言下
终端环境默认代码页不同
中文系统采用ANSI
英文不清楚
可以chcp看看是不是936

**Comment by Minecrafter-Pythoner** [comment]
两台设备cmd执行chcp的输出均为437
（注：均测试过使用Windows Terminal/Windows Console Host）
![image](https://github.com/user-attachments/assets/9e4f3e81-77bb-416b-b6c1-4649d76467f4)

**Comment by LY-Xiang** [comment]
437是美国windows对应默认代码页

**Comment by LY-Xiang** [comment]
936是中文的代码页

**Comment by LY-Xiang** [comment]
我可以尝试在脚本中加入改变代码页的指令

**Comment by LY-Xiang** [comment]
可尝试该[action](https://github.com/Mzdyl/LiteLoaderQQNT_Install/actions/runs/10233586060)中打包的文件
虽然我也不确定有没有解决(

**Comment by Minecrafter-Pythoner** [comment]
很可惜似乎没有效果
<img width="665" alt="image" src="https://github.com/user-attachments/assets/cf7a887b-25cc-4995-a2ac-835e35ae046a">

**Comment by LY-Xiang** [comment]
我建个en-us环境的虚拟机试试吧

**Comment by sinanliu001** [comment]
先处理下unicode语言
![image](https://github.com/user-attachments/assets/1e8e25ba-23ea-4d62-a1ee-533f797ac9f9)
![image](https://github.com/user-attachments/assets/dd2152c0-45d8-4b35-9bbe-c80c137d3896)

**Comment by Minecrafter-Pythoner** [comment]
![image](https://github.com/user-attachments/assets/cc19c31e-a70e-4a40-983d-c247dd6d1685)
请问是应该改成简体中文吗？

**Comment by sinanliu001** [comment]
> ![image](https://private-user-images.githubusercontent.com/58333458/393520676-cc19c31e-a70e-4a40-983d-c247dd6d1685.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDg2OTMsIm5iZiI6MTczMzc0ODM5MywicGF0aCI6Ii81ODMzMzQ1OC8zOTM1MjA2NzYtY2MxOWMzMWUtYTcwZS00YTQwLTk4M2QtYzI0N2RkNmQxNjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDEyNDYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTM3MDkzMjI1MTVlOTAyN2RkODI0MjA1NjU2OGUyMGQxMWZmMzRhZTcyNThhODUxNWQwZDc1M2FhNmNkYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o903aMAfjO-zfIGpWE7UFMJ0d4_3AdLhk4FW2QM_W94) 请问是应该改成简体中文吗？

是的。最后重启就好

**Comment by Minecrafter-Pythoner** [comment]
修改非Unicode程序语言后能正常显示汉字了，谢谢！
![image](https://github.com/user-attachments/assets/1e2b4790-b857-42fc-9940-6604147b9bf5)

**Comment by LY-Xiang** [comment]
😨
忘了还有系统unicode设置了(
