### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by azkbbys** [Mzdyl/LiteLoaderQQNT_Install#92]
### 问题类型
请选择一个:
- [x] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [ ] macOS
- [ ] Linux
- [x] Windows

### 运行版本
请填写您的运行版本:1.14

### 描述
简要描述您的问题:报错“[1104] Cannot open PyInstaller archive from executable (C:\Users\Administrator\Downloads\install_windows-1.14.exe) or external archive (C:\Users\Administrator\Downloads\install_windows-1.14.pkg)”

### 错误截图
请粘贴错误截图:
![image](https://github.com/user-attachments/assets/4c938162-06ba-4165-ac19-9adb8d5c8f94)

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:无

**Comment by Mzdyl** [comment]
可以尝试使用 nuitka 版本
[install_windows_nuitka.exe](https://github.com/Mzdyl/LiteLoaderQQNT_Install/releases/download/1.14/install_windows_nuitka.exe)
bug 涉及 pyinstaller，暂时无法处理，可能是下载过程出现问题，导致安装包自检失败导致的
