### ISSUE TITLE
修补后QQ白屏

### ISSUE THREAD

**Issue by LiamBlog** [Mzdyl/LiteLoaderQQNT_Install#94]
### 问题类型
请选择一个:
- [√] Bug 反馈
- [ ] 功能改进
- [ ] 其他
- [ ] 与作者吹水（bushi

### 运行平台
请选择您的运行平台:
- [ ] macOS
- [ ] Linux
- [√] Windows

### 运行版本
请填写您的运行版本:install_windows-1.14
                                  QQ：QQ_9.9.11_240606_x64_01

### 描述
简要描述您的问题:修补完成后，QQ白屏无法打开

### 错误截图
请粘贴错误截图:
![a221eea67bcac30c63eacc3760008b27](https://github.com/user-attachments/assets/f1271154-a43e-433d-9db2-2f5691241560)
![10cd0b0c15f4729d2da71edfae622308](https://github.com/user-attachments/assets/6bb5db63-0b62-48fe-9882-fce1fb0d3a8f)

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by Mzdyl** [comment]
https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/361

和 LiteLoaderQQNT 本体有关
目前测试只要存在热更新即会出现此bug
可以手动重装成最新版本避免热更新或等待 LiteLoaderQQNT 更新
即 **避免** `C:\Program Files\Tencent\QQNT\resources\app\versions`内 存在热更QQ

**Comment by Calvariaa** [comment]
QQ_9.9.11_240606_x64_01
尝试使用旧版liteloader以兼容QQNT24568
