### ISSUE TITLE
跟“安装完后，打开QQ时出现了错误”问题一样

### ISSUE THREAD

**Issue by KiraBoXin** [Mzdyl/LiteLoaderQQNT_Install#99]
### 问题类型
请选择一个:
- [ ] Bug 反馈

### 运行平台
请选择您的运行平台:

- [ ] Windows

### 运行版本
请填写您的运行版本:1.14

### 描述
简要描述您的问题:安装过程中，自动修改了插件存放路径导致无法打开QQ
下方截图为第二次安装已经出错
第一次安装时会弹出是否使用修改过的路径，但默认否定且会修改去Document文件夹，导致自动安装完后找不到插件路径？

### 错误截图
请粘贴错误截图:
![image](https://github.com/user-attachments/assets/4bfb6ebb-4f70-439d-8c5b-743ac56c7a0c)

若为 Bug 反馈且附带截图将被优先解决
### 附加信息
如果有任何其他相关信息，请注明:

**Comment by KiraBoXin** [comment]
好像也不能用来更新1.2.0的loder

**Comment by KiraBoXin** [comment]
看到pre1.14中提到会使用用户文档文件夹，那应该是没有复制插件到文档文件夹导致无法打开qq

**Comment by Mzdyl** [comment]
可以提供一下QQ 错误 截图吗
应该是 插件冲突 或者 插件缺依赖
安装器会自动复制旧版插件数据到新目录的
以及可以更新LiteloaderQQNT 1.2.0（ 不过LL 1.2.0 与 QQ 热更新 有冲突会导致登陆白屏
